// Code generated by cmd/codegen. DO NOT EDIT.
// Frontend enum: material_status_type.

import * as v from "valibot";

import { MATERIAL_STATUS_TYPE_VALUES } from "@/types/enums/materialStatusType.gen";
import { defaultTranslate, type TranslateFn } from "@/schemas/common";

export const createMaterialStatusTypeSchemas = (t: TranslateFn) => {
	const MaterialStatusTypeSchema = v.picklist(
		MATERIAL_STATUS_TYPE_VALUES,
		t("validation.required"),
	);

	return { MaterialStatusTypeSchema };
};

const materialStatusTypeSchemas = createMaterialStatusTypeSchemas(defaultTranslate);

export const MaterialStatusTypeSchema = materialStatusTypeSchemas.MaterialStatusTypeSchema;
