// Code generated by cmd/codegen. DO NOT EDIT.

import type { RouteRecordRaw } from "vue-router";

import type { ApplicationRouteManifestItem } from "@katren/vue-business-app/application-routes";
const ConstructionSiteList = () => import("@/views/constructionSite/ConstructionSiteList.vue");
const ConstructionSiteEditPage = () => import("@/views/constructionSite/ConstructionSiteEditPage.vue");
const ContactList = () => import("@/views/contact/ContactList.vue");
const ContactEditPage = () => import("@/views/contact/ContactEditPage.vue");
const EmployeePostList = () => import("@/views/employeePost/EmployeePostList.vue");
const EmployeePostEditPage = () => import("@/views/employeePost/EmployeePostEditPage.vue");
const MaterialList = () => import("@/views/material/MaterialList.vue");
const MaterialEditPage = () => import("@/views/material/MaterialEditPage.vue");
const MaterialConsumptionList = () => import("@/views/materialConsumption/MaterialConsumptionList.vue");
const MaterialConsumptionEditPage = () => import("@/views/materialConsumption/MaterialConsumptionEditPage.vue");
const MaterialReceiptList = () => import("@/views/materialReceipt/MaterialReceiptList.vue");
const MaterialReceiptEditPage = () => import("@/views/materialReceipt/MaterialReceiptEditPage.vue");
const MaterialTransferList = () => import("@/views/materialTransfer/MaterialTransferList.vue");
const MaterialTransferEditPage = () => import("@/views/materialTransfer/MaterialTransferEditPage.vue");
const MaterialTypeList = () => import("@/views/materialType/MaterialTypeList.vue");
const MaterialTypeEditPage = () => import("@/views/materialType/MaterialTypeEditPage.vue");
const MaxUserList = () => import("@/views/maxUser/MaxUserList.vue");
const MeasureUnitList = () => import("@/views/measureUnit/MeasureUnitList.vue");
const MeasureUnitEditPage = () => import("@/views/measureUnit/MeasureUnitEditPage.vue");
const NotificationTemplateList = () => import("@/views/notificationTemplate/NotificationTemplateList.vue");
const NotificationTemplateEditPage = () => import("@/views/notificationTemplate/NotificationTemplateEditPage.vue");
const SupplierList = () => import("@/views/supplier/SupplierList.vue");
const SupplierEditPage = () => import("@/views/supplier/SupplierEditPage.vue");

export interface GeneratedRouteManifestEntry {
	route: RouteRecordRaw;
	registry: ApplicationRouteManifestItem;
}

const defineGeneratedRoute = (
	route: RouteRecordRaw,
	registry: Omit<ApplicationRouteManifestItem, "name" | "path">,
): GeneratedRouteManifestEntry => ({
	route,
	registry: {
		name: String(route.name ?? ""),
		path: route.path,
		...registry,
	},
});

export const generatedRouteManifest: GeneratedRouteManifestEntry[] = [
	defineGeneratedRoute(
		{
			path: "/construction-sites",
			name: "constructionSites",
			component: ConstructionSiteList,
		},
		{
			descr: "Объекты строительства",
			section: "Справочники",
			icon: "pi pi-car",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/construction-sites/new",
			name: "constructionSiteCreate",
			component: ConstructionSiteEditPage,
		},
		{
			descr: "Новый объект строительства",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/construction-sites/:id",
			name: "constructionSiteEdit",
			component: ConstructionSiteEditPage,
			props: true,
		},
		{
			descr: "объект строительства",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/contacts",
			name: "contacts",
			component: ContactList,
		},
		{
			descr: "Контакты",
			section: "Справочники",
			icon: "pi pi-id-card",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/contacts/new",
			name: "contactCreate",
			component: ContactEditPage,
		},
		{
			descr: "Новый контакт",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/contacts/:id",
			name: "contactEdit",
			component: ContactEditPage,
			props: true,
		},
		{
			descr: "контакт",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/employee-post",
			name: "employeePosts",
			component: EmployeePostList,
		},
		{
			descr: "Должности",
			section: "Справочники",
			icon: "pi pi-sitemap",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/employee-post/new",
			name: "employeePostCreate",
			component: EmployeePostEditPage,
		},
		{
			descr: "Должности",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/employee-post/:id",
			name: "employeePostEdit",
			component: EmployeePostEditPage,
			props: true,
		},
		{
			descr: "Должности",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material",
			name: "materials",
			component: MaterialList,
		},
		{
			descr: "Материалы",
			section: "Справочники",
			icon: "pi pi-car",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material/new",
			name: "materialCreate",
			component: MaterialEditPage,
		},
		{
			descr: "Новвый материал",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material/:id",
			name: "materialEdit",
			component: MaterialEditPage,
			props: true,
		},
		{
			descr: "Материал",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-consumptions",
			name: "materialConsumptions",
			component: MaterialConsumptionList,
		},
		{
			descr: "Списания материалов",
			section: "Документы",
			icon: "pi pi-upload",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-consumptions/new",
			name: "materialConsumptionCreate",
			component: MaterialConsumptionEditPage,
		},
		{
			descr: "Новое списание материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-consumptions/:id",
			name: "materialConsumptionEdit",
			component: MaterialConsumptionEditPage,
			props: true,
		},
		{
			descr: "Списание материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-receipts",
			name: "materialReceipts",
			component: MaterialReceiptList,
		},
		{
			descr: "Поступления материалов",
			section: "Документы",
			icon: "pi pi-download",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-receipts/new",
			name: "materialReceiptCreate",
			component: MaterialReceiptEditPage,
		},
		{
			descr: "Новое поступление материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-receipts/:id",
			name: "materialReceiptEdit",
			component: MaterialReceiptEditPage,
			props: true,
		},
		{
			descr: "Поступление материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-transfers",
			name: "materialTransfers",
			component: MaterialTransferList,
		},
		{
			descr: "Перемещения материалов",
			section: "Документы",
			icon: "pi pi-arrow-right-arrow-left",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-transfers/new",
			name: "materialTransferCreate",
			component: MaterialTransferEditPage,
		},
		{
			descr: "Новое перемещение материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-transfers/:id",
			name: "materialTransferEdit",
			component: MaterialTransferEditPage,
			props: true,
		},
		{
			descr: "Перемещение материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-types",
			name: "materialTypes",
			component: MaterialTypeList,
		},
		{
			descr: "Виды материалов",
			section: "Справочники",
			icon: "pi pi-bookmark",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-types/new",
			name: "materialTypeCreate",
			component: MaterialTypeEditPage,
		},
		{
			descr: "Виды материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/material-types/:id",
			name: "materialTypeEdit",
			component: MaterialTypeEditPage,
			props: true,
		},
		{
			descr: "Виды материалов",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/max-users",
			name: "maxUsers",
			component: MaxUserList,
		},
		{
			descr: "Пользователи MAX",
			section: "Справочники",
			icon: "pi pi-id-card",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/measure-unit",
			name: "measureUnits",
			component: MeasureUnitList,
		},
		{
			descr: "Единицы измерения",
			section: "Справочники",
			icon: "pi pi-car",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/measure-unit/new",
			name: "measureUnitCreate",
			component: MeasureUnitEditPage,
		},
		{
			descr: "Новaя единица измерения",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/measure-unit/:id",
			name: "measureUnitEdit",
			component: MeasureUnitEditPage,
			props: true,
		},
		{
			descr: "единица измерения",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/notification_template",
			name: "notificationTemplates",
			component: NotificationTemplateList,
		},
		{
			descr: "Шаблоны уведомлений",
			section: "Справочники",
			icon: "pi pi-megaphone",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/notification_template/new",
			name: "notificationTemplateCreate",
			component: NotificationTemplateEditPage,
		},
		{
			descr: "Новый шаблон уведомления",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/notification_template/:id",
			name: "notificationTemplateEdit",
			component: NotificationTemplateEditPage,
			props: true,
		},
		{
			descr: "Шаблон уведомления",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/supplier",
			name: "suppliers",
			component: SupplierList,
		},
		{
			descr: "Поставщики",
			section: "Справочники",
			icon: "pi pi-car",
			menu_available: true,
		},
	),
	defineGeneratedRoute(
		{
			path: "/supplier/new",
			name: "supplierCreate",
			component: SupplierEditPage,
		},
		{
			descr: "Новый поставщик",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
	defineGeneratedRoute(
		{
			path: "/supplier/:id",
			name: "supplierEdit",
			component: SupplierEditPage,
			props: true,
		},
		{
			descr: "Поставщик",
			section: "Формы",
			icon: null,
			menu_available: false,
		},
	),
];
