// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { constructionSiteApi } from "@/api/constructionSite.gen";
import type { ConstructionSite } from "@/types/constructionSite.gen";
import type {
	ConstructionSiteKey,
	ConstructionSiteNew,
	ConstructionSiteUpd,
} from "@/types/constructionSite.gen";

type ListModel = ConstructionSite;
type CreateModel = ConstructionSiteNew;
type UpdateModel = ConstructionSiteUpd;
const commands: GridCommand<ListModel, ConstructionSiteKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const constructionSiteCollection = defineCollection<
	ListModel,
	ConstructionSiteKey,
	CreateModel,
	UpdateModel,
	ConstructionSite
>({
	titleKey: "ConstructionSite.title",
	api: constructionSiteApi,
	columns: [
		{
			field: "id",
			headerKey: "ConstructionSite.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "ConstructionSite.fields.name",
			sortable: true,
			width: "32rem",
		},
		{
			field: "is_active",
			headerKey: "ConstructionSite.fields.is_active",
			sortable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "constructionSiteCreate" }),
		edit: (row) => ({
			name: "constructionSiteEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "constructionSiteCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "constructionSite-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
