// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { contactApi } from "@/api/contact.gen";
import type { Contact } from "@/types/contact.gen";
import type {
	ContactKey,
	ContactNew,
	ContactUpd,
} from "@/types/contact.gen";

type ListModel = Contact;
type CreateModel = ContactNew;
type UpdateModel = ContactUpd;
const commands: GridCommand<ListModel, ContactKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const contactCollection = defineCollection<
	ListModel,
	ContactKey,
	CreateModel,
	UpdateModel,
	Contact
>({
	titleKey: "Contact.title",
	api: contactApi,
	columns: [
		{
			field: "id",
			headerKey: "Contact.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "Contact.fields.name",
			sortable: true,
			width: "32rem",
		},
		{
			field: "phone",
			headerKey: "Contact.fields.phone",
			sortable: true,
			width: "16rem",
		},
		{
			field: "email",
			headerKey: "Contact.fields.email",
			sortable: true,
			width: "16rem",
		},
		{
			field: "is_active",
			headerKey: "Contact.fields.is_active",
			sortable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "contactCreate" }),
		edit: (row) => ({
			name: "contactEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "contactCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "contact-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
