// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { employeePostApi } from "@/api/employeePost.gen";
import type { EmployeePost } from "@/types/employeePost.gen";
import type {
	EmployeePostKey,
	EmployeePostNew,
	EmployeePostUpd,
} from "@/types/employeePost.gen";

type ListModel = EmployeePost;
type CreateModel = EmployeePostNew;
type UpdateModel = EmployeePostUpd;
const createRow = (): ListModel => ({
	id: 0,
	name: "",
	is_active: true,
});

const createModel = (row: ListModel): CreateModel => ({
	name: row.name,
	is_active: row.is_active,
});
const commands: GridCommand<ListModel, EmployeePostKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const employeePostCollection = defineCollection<
	ListModel,
	EmployeePostKey,
	CreateModel,
	UpdateModel,
	EmployeePost
>({
	titleKey: "EmployeePost.title",
	api: employeePostApi,
	columns: [
		{
			field: "id",
			headerKey: "EmployeePost.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "EmployeePost.fields.name",
			sortable: true,
			editable: true,
			width: "32rem",
		},
		{
			field: "is_active",
			headerKey: "EmployeePost.fields.is_active",
			sortable: true,
			editable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "employeePostCreate" }),
		edit: (row) => ({
			name: "employeePostEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "employeePostCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "inline",
	createRow,
	createModel,
	stateKey: "employeePost-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
