// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { materialApi } from "@/api/material.gen";
import type { MaterialList } from "@/types/materialList.gen";
import type {
	Material,
	MaterialKey,
	MaterialNew,
	MaterialUpd,
} from "@/types/material.gen";

type ListModel = MaterialList;
type CreateModel = MaterialNew;
type UpdateModel = MaterialUpd;
const commands: GridCommand<ListModel, MaterialKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialCollection = defineCollection<
	ListModel,
	MaterialKey,
	CreateModel,
	UpdateModel,
	Material
>({
	titleKey: "Material.title",
	api: materialApi,
	columns: [
		{
			field: "id",
			headerKey: "Material.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "Material.fields.name",
			sortable: true,
			width: "32rem",
		},
		{
			field: "is_active",
			headerKey: "Material.fields.is_active",
			sortable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "materialCreate" }),
		edit: (row) => ({
			name: "materialEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "materialCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "material-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
