// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { constructionManagerReference, constructionSiteReference } from "@/references/inventoryReferences";
import { materialRequestApi } from "@/api/materialRequest.gen";
import type { MaterialRequestList } from "@/types/materialRequestList.gen";
import type {
	MaterialRequest,
	MaterialRequestKey,
	MaterialRequestNew,
	MaterialRequestUpd,
} from "@/types/materialRequest.gen";

type ListModel = MaterialRequestList;
type CreateModel = MaterialRequestNew;
type UpdateModel = MaterialRequestUpd;
const formatDateTime = (value: unknown): string => value instanceof Date
	? value.toLocaleString("ru-RU")
	: "";
const commands: GridCommand<ListModel, MaterialRequestKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialRequestCollection = defineCollection<
	ListModel,
	MaterialRequestKey,
	CreateModel,
	UpdateModel,
	MaterialRequest
>({
	titleKey: "MaterialRequest.title",
	api: materialRequestApi,
	columns: [
		{
			field: "id",
			headerKey: "MaterialRequest.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "date",
			headerKey: "MaterialRequest.fields.date",
			sortable: true,
			dataType: "datetime",
			format: formatDateTime,
			width: "12rem",
		},
		{
			field: "construction_site_id",
			headerKey: "MaterialRequest.fields.construction_site_id",
			sortable: true,
			sortField: "construction_site->>'descr'",
			dataType: "reference",
			reference: constructionSiteReference,
			referenceField: "construction_site",
			width: "16rem",
		},
		{
			field: "construction_manager_id",
			headerKey: "MaterialRequest.fields.construction_manager_id",
			sortable: true,
			sortField: "construction_manager->>'descr'",
			dataType: "reference",
			reference: constructionManagerReference,
			referenceField: "construction_manager",
			width: "16rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "materialRequestCreate" }),
		edit: (row) => ({
			name: "materialRequestEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "materialRequestCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "materialRequest-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
