// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { materialTypeApi } from "@/api/materialType.gen";
import type { MaterialType } from "@/types/materialType.gen";
import type {
	MaterialTypeKey,
	MaterialTypeNew,
	MaterialTypeUpd,
} from "@/types/materialType.gen";

type ListModel = MaterialType;
type CreateModel = MaterialTypeNew;
type UpdateModel = MaterialTypeUpd;
const createRow = (): ListModel => ({
	id: 0,
	code: "",
	name: "",
	is_active: true,
});

const createModel = (row: ListModel): CreateModel => ({
	code: row.code,
	name: row.name,
	is_active: row.is_active,
});
const commands: GridCommand<ListModel, MaterialTypeKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialTypeCollection = defineCollection<
	ListModel,
	MaterialTypeKey,
	CreateModel,
	UpdateModel,
	MaterialType
>({
	titleKey: "MaterialType.title",
	api: materialTypeApi,
	columns: [
		{
			field: "id",
			headerKey: "MaterialType.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "code",
			headerKey: "MaterialType.fields.code",
			sortable: true,
			editable: true,
			width: "16rem",
		},
		{
			field: "name",
			headerKey: "MaterialType.fields.name",
			sortable: true,
			editable: true,
			width: "32rem",
		},
		{
			field: "is_active",
			headerKey: "MaterialType.fields.is_active",
			sortable: true,
			editable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "materialTypeCreate" }),
		edit: (row) => ({
			name: "materialTypeEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "materialTypeCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "inline",
	createRow,
	createModel,
	stateKey: "materialType-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
