// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { materialConsumptionApi } from "@/api/materialConsumption.gen";
import type { MaterialConsumptionList } from "@/types/materialConsumptionList.gen";
import type {
	MaterialConsumption,
	MaterialConsumptionKey,
	MaterialConsumptionNew,
	MaterialConsumptionUpd,
} from "@/types/materialConsumption.gen";

type ListModel = MaterialConsumptionList;
type CreateModel = MaterialConsumptionNew;
type UpdateModel = MaterialConsumptionUpd;
const formatDate = (value: unknown): string => value instanceof Date
	? value.toLocaleDateString("ru-RU")
	: "";
const commands: GridCommand<ListModel, MaterialConsumptionKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialConsumptionCollection = defineCollection<
	ListModel,
	MaterialConsumptionKey,
	CreateModel,
	UpdateModel,
	MaterialConsumption
>({
	titleKey: "MaterialConsumption.title",
	api: materialConsumptionApi,
	columns: [
		{
			field: "id",
			headerKey: "MaterialConsumption.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "date",
			headerKey: "MaterialConsumption.fields.date",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "10rem",
		},
		{
			field: "construction_site_id",
			headerKey: "MaterialConsumption.fields.construction_site_id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "12rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "materialConsumptionCreate" }),
		edit: (row) => ({
			name: "materialConsumptionEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "materialConsumptionCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "materialConsumption-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
