// Code generated by cmd/codegen. DO NOT EDIT.

import { defineCollection, type GridCommand } from "@katren/vue-collection-lib";
import {
	constructionSiteReference,
	materialReference,
} from "@/references/inventoryReferences";
import { MATERIAL_STATUS_TYPE_VALUES } from "@/types/enums/materialStatusType.gen";
import { materialStatusApi } from "@/api/materialStatus.gen";
import type { MaterialStatusList } from "@/types/materialStatusList.gen";
import type {
	MaterialStatus,
	MaterialStatusKey,
	MaterialStatusNew,
	MaterialStatusUpd,
} from "@/types/materialStatus.gen";

type ListModel = MaterialStatusList;
type CreateModel = MaterialStatusNew;
type UpdateModel = MaterialStatusUpd;
const createRow = (): ListModel => ({
	id: 0,
	created_at: new Date(),
	construction_site_id: null,
	construction_site: null,
	material_id: 0,
	material: {},
	status: "at_work",
	is_active: true,
});

const createModel = (row: ListModel): CreateModel => ({
	created_at: row.created_at,
	construction_site_id: row.construction_site_id ?? 0,
	material_id: row.material_id,
	status: row.status,
	is_active: row.is_active,
});
const formatDateTime = (value: unknown): string =>
	value instanceof Date ? value.toLocaleString("ru-RU") : "";
const commands: GridCommand<ListModel, MaterialStatusKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialStatusCollection = defineCollection<
	ListModel,
	MaterialStatusKey,
	CreateModel,
	UpdateModel,
	MaterialStatus
>({
	titleKey: "MaterialStatus.title",
	api: materialStatusApi,
	columns: [
		{
			field: "id",
			headerKey: "MaterialStatus.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "created_at",
			headerKey: "MaterialStatus.fields.created_at",
			sortable: true,
			editable: true,
			dataType: "datetime",
			format: formatDateTime,
			width: "14rem",
		},
		{
			field: "construction_site_id",
			headerKey: "MaterialStatus.fields.construction_site_id",
			sortable: true,
			sortField: "construction_site->>'descr'",
			editable: true,
			dataType: "reference",
			reference: constructionSiteReference,
			referenceField: "construction_site",
			editorProps: {
				showClear: false,
			},
			width: "18rem",
		},
		{
			field: "material_id",
			headerKey: "MaterialStatus.fields.material_id",
			sortable: true,
			sortField: "material->>'descr'",
			editable: true,
			dataType: "reference",
			reference: materialReference,
			referenceField: "material",
			width: "16rem",
		},
		{
			field: "status",
			headerKey: "MaterialStatus.fields.status",
			sortable: true,
			editable: true,
			dataType: "enum",
			enumOptions: MATERIAL_STATUS_TYPE_VALUES.map(
				(value) => ({
					value,
					labelKey: `MaterialStatusType.${value}`,
				}),
			),
			editorProps: {
				showClear: false,
			},
			width: "16rem",
		},
		{
			field: "is_active",
			headerKey: "MaterialStatus.fields.is_active",
			sortable: true,
			editable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {},
	editMode: "inline",
	createRow,
	createModel,
	stateKey: "materialStatus-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
