// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { materialTransferApi } from "@/api/materialTransfer.gen";
import type { MaterialTransferList } from "@/types/materialTransferList.gen";
import type {
	MaterialTransfer,
	MaterialTransferKey,
	MaterialTransferNew,
	MaterialTransferUpd,
} from "@/types/materialTransfer.gen";

type ListModel = MaterialTransferList;
type CreateModel = MaterialTransferNew;
type UpdateModel = MaterialTransferUpd;
const formatDate = (value: unknown): string => value instanceof Date
	? value.toLocaleDateString("ru-RU")
	: "";
const commands: GridCommand<ListModel, MaterialTransferKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialTransferCollection = defineCollection<
	ListModel,
	MaterialTransferKey,
	CreateModel,
	UpdateModel,
	MaterialTransfer
>({
	titleKey: "MaterialTransfer.title",
	api: materialTransferApi,
	columns: [
		{
			field: "id",
			headerKey: "MaterialTransfer.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "date",
			headerKey: "MaterialTransfer.fields.date",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "10rem",
		},
		{
			field: "source_construction_site_id",
			headerKey: "MaterialTransfer.fields.source_construction_site_id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "12rem",
		},
		{
			field: "destination_construction_site_id",
			headerKey: "MaterialTransfer.fields.destination_construction_site_id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "12rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "materialTransferCreate" }),
		edit: (row) => ({
			name: "materialTransferEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "materialTransferCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "materialTransfer-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
