// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { materialReceiptApi } from "@/api/materialReceipt.gen";
import type { MaterialReceiptList } from "@/types/materialReceiptList.gen";
import type {
	MaterialReceipt,
	MaterialReceiptKey,
	MaterialReceiptNew,
	MaterialReceiptUpd,
} from "@/types/materialReceipt.gen";

type ListModel = MaterialReceiptList;
type CreateModel = MaterialReceiptNew;
type UpdateModel = MaterialReceiptUpd;
const formatDate = (value: unknown): string => value instanceof Date
	? value.toLocaleDateString("ru-RU")
	: "";
const commands: GridCommand<ListModel, MaterialReceiptKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialReceiptCollection = defineCollection<
	ListModel,
	MaterialReceiptKey,
	CreateModel,
	UpdateModel,
	MaterialReceipt
>({
	titleKey: "MaterialReceipt.title",
	api: materialReceiptApi,
	columns: [
		{
			field: "id",
			headerKey: "MaterialReceipt.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "date",
			headerKey: "MaterialReceipt.fields.date",
			sortable: true,
			dataType: "date",
			format: formatDate,
			width: "10rem",
		},
		{
			field: "number",
			headerKey: "MaterialReceipt.fields.number",
			sortable: true,
			width: "12rem",
		},
		{
			field: "construction_site_id",
			headerKey: "MaterialReceipt.fields.construction_site_id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "12rem",
		},
		{
			field: "supplier_id",
			headerKey: "MaterialReceipt.fields.supplier_id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "12rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "materialReceiptCreate" }),
		edit: (row) => ({
			name: "materialReceiptEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "materialReceiptCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "materialReceipt-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
