// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { materialRequestStatusApi } from "@/api/materialRequestStatus.gen";
import type { MaterialRequestStatus } from "@/types/materialRequestStatus.gen";
import type {
	MaterialRequestStatusKey,
	MaterialRequestStatusUpd,
} from "@/types/materialRequestStatus.gen";

type ListModel = MaterialRequestStatus;
type CreateModel = never;
type UpdateModel = MaterialRequestStatusUpd;
const commands: GridCommand<ListModel, MaterialRequestStatusKey>[] = [
	{ name: "edit" },
	{ name: "search" },
	{ name: "refresh" },
];

export const materialRequestStatusCollection = defineCollection<
	ListModel,
	MaterialRequestStatusKey,
	CreateModel,
	UpdateModel,
	MaterialRequestStatus
>({
	titleKey: "MaterialRequestStatus.title",
	api: materialRequestStatusApi,
	columns: [
		{
			field: "id",
			headerKey: "MaterialRequestStatus.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "code",
			headerKey: "MaterialRequestStatus.fields.code",
			sortable: true,
			width: "16rem",
		},
		{
			field: "name",
			headerKey: "MaterialRequestStatus.fields.name",
			sortable: true,
			editable: true,
			width: "28rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
	},
	editMode: "inline",
	stateKey: "materialRequestStatus-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
