// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { measureUnitApi } from "@/api/measureUnit.gen";
import type { MeasureUnit } from "@/types/measureUnit.gen";
import type {
	MeasureUnitKey,
	MeasureUnitNew,
	MeasureUnitUpd,
} from "@/types/measureUnit.gen";

type ListModel = MeasureUnit;
type CreateModel = MeasureUnitNew;
type UpdateModel = MeasureUnitUpd;
const commands: GridCommand<ListModel, MeasureUnitKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const measureUnitCollection = defineCollection<
	ListModel,
	MeasureUnitKey,
	CreateModel,
	UpdateModel,
	MeasureUnit
>({
	titleKey: "MeasureUnit.title",
	api: measureUnitApi,
	columns: [
		{
			field: "id",
			headerKey: "MeasureUnit.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "MeasureUnit.fields.name",
			sortable: true,
			width: "32rem",
		},
		{
			field: "is_active",
			headerKey: "MeasureUnit.fields.is_active",
			sortable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "measureUnitCreate" }),
		edit: (row) => ({
			name: "measureUnitEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "measureUnitCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "measureUnit-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
