// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { notificationTemplateApi } from "@/api/notificationTemplate.gen";
import type { NotificationTemplate } from "@/types/notificationTemplate.gen";
import type {
	NotificationTemplateKey,
	NotificationTemplateNew,
	NotificationTemplateUpd,
} from "@/types/notificationTemplate.gen";

type ListModel = NotificationTemplate;
type CreateModel = NotificationTemplateNew;
type UpdateModel = NotificationTemplateUpd;
const commands: GridCommand<ListModel, NotificationTemplateKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const notificationTemplateCollection = defineCollection<
	ListModel,
	NotificationTemplateKey,
	CreateModel,
	UpdateModel,
	NotificationTemplate
>({
	titleKey: "NotificationTemplate.title",
	api: notificationTemplateApi,
	columns: [
		{
			field: "id",
			headerKey: "NotificationTemplate.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "code",
			headerKey: "NotificationTemplate.fields.code",
			sortable: true,
			width: "32rem",
		},
		{
			field: "is_active",
			headerKey: "NotificationTemplate.fields.is_active",
			sortable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "notificationTemplateCreate" }),
		edit: (row) => ({
			name: "notificationTemplateEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "notificationTemplateCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "notificationTemplate-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
