// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { orderImportanceApi } from "@/api/orderImportance.gen";
import type { OrderImportance } from "@/types/orderImportance.gen";
import type {
	OrderImportanceKey,
	OrderImportanceNew,
	OrderImportanceUpd,
} from "@/types/orderImportance.gen";

type ListModel = OrderImportance;
type CreateModel = OrderImportanceNew;
type UpdateModel = OrderImportanceUpd;
const createRow = (): ListModel => ({
	id: 0,
	name: "",
	sort_order: 0,
	is_active: true,
});

const createModel = (row: ListModel): CreateModel => ({
	name: row.name,
	sort_order: row.sort_order,
	is_active: row.is_active,
});
const commands: GridCommand<ListModel, OrderImportanceKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const orderImportanceCollection = defineCollection<
	ListModel,
	OrderImportanceKey,
	CreateModel,
	UpdateModel,
	OrderImportance
>({
	titleKey: "OrderImportance.title",
	api: orderImportanceApi,
	columns: [
		{
			field: "id",
			headerKey: "OrderImportance.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "OrderImportance.fields.name",
			sortable: true,
			editable: true,
			width: "28rem",
		},
		{
			field: "sort_order",
			headerKey: "OrderImportance.fields.sort_order",
			sortable: true,
			editable: true,
			dataType: "number",
			align: "right",
			width: "10rem",
		},
		{
			field: "is_active",
			headerKey: "OrderImportance.fields.is_active",
			sortable: true,
			editable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
	},
	editMode: "inline",
	createRow,
	createModel,
	stateKey: "orderImportance-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
