// Code generated by cmd/codegen. DO NOT EDIT.

import {
	defineCollection,
	type GridCommand,
} from "@katren/vue-collection-lib";
import { supplierApi } from "@/api/supplier.gen";
import type { Supplier } from "@/types/supplier.gen";
import type {
	SupplierKey,
	SupplierNew,
	SupplierUpd,
} from "@/types/supplier.gen";

type ListModel = Supplier;
type CreateModel = SupplierNew;
type UpdateModel = SupplierUpd;
const commands: GridCommand<ListModel, SupplierKey>[] = [
	{ name: "create" },
	{ name: "edit" },
	{ name: "copy" },
	{ name: "delete" },
	{ name: "search" },
	{ name: "refresh" },
];

export const supplierCollection = defineCollection<
	ListModel,
	SupplierKey,
	CreateModel,
	UpdateModel,
	Supplier
>({
	titleKey: "Supplier.title",
	api: supplierApi,
	columns: [
		{
			field: "id",
			headerKey: "Supplier.fields.id",
			sortable: true,
			dataType: "number",
			align: "right",
			width: "8rem",
		},
		{
			field: "name",
			headerKey: "Supplier.fields.name",
			sortable: true,
			width: "32rem",
		},
		{
			field: "inn",
			headerKey: "Supplier.fields.inn",
			sortable: true,
			width: "8rem",
		},
		{
			field: "is_active",
			headerKey: "Supplier.fields.is_active",
			sortable: true,
			dataType: "boolean",
			width: "8rem",
		},
	],
	commands,
	dataKey: "id",
	getKey: (row) => ({
		id: row.id,
	}),
	routes: {
		create: () => ({ name: "supplierCreate" }),
		edit: (row) => ({
			name: "supplierEdit",
			params: {
				id: String(row.id),
			},
		}),
		copy: (row) => ({
			name: "supplierCreate",
			query: {
				copy_id: String(row.id),
			},
		}),
	},
	editMode: "page",
	stateKey: "supplier-grid",
	pageSize: 30,
	showCommandShortcuts: false,
});
