// Code generated by cmd/codegen. DO NOT EDIT.

export interface ContactDTO {
	id: number;
	name: string;
	phone: string;
	email: string | null;
	employee_post_id: number | null;
	is_active: boolean;
	search: string | null;
}

export interface Contact {
	id: number;
	name: string;
	phone: string;
	email: string | null;
	employee_post_id: number | null;
	is_active: boolean;
	search: string | null;
}

export type ContactKey = Pick<
	Contact,
	"id"
>;
export type ContactNew = Pick<
	Contact,
	"name" | "phone" | "email" | "employee_post_id" | "is_active"
>;
export type ContactUpd = Partial<Pick<
	Contact,
	"name" | "phone" | "email" | "employee_post_id" | "is_active"
>>;

export interface ContactUpdate {
	key: ContactKey;
	model: ContactUpd;
}
