// Code generated by cmd/codegen. DO NOT EDIT.

export interface EmployeePostDTO {
	id: number;
	name: string;
	is_active: boolean;
}

export interface EmployeePost {
	id: number;
	name: string;
	is_active: boolean;
}

export type EmployeePostKey = Pick<
	EmployeePost,
	"id"
>;
export type EmployeePostNew = Pick<
	EmployeePost,
	"name" | "is_active"
>;
export type EmployeePostUpd = Partial<Pick<
	EmployeePost,
	"name" | "is_active"
>>;

export interface EmployeePostUpdate {
	key: EmployeePostKey;
	model: EmployeePostUpd;
}
