// Code generated by cmd/codegen. DO NOT EDIT.

export interface EntityContactListDTO {
	id: number;
	entity_type: string;
	entity_id: number;
	entity: Record<string, unknown>;
	contact_id: number;
	contact: Record<string, unknown>;
	contact_attrs: Record<string, unknown>;
	is_active: boolean;
}

export interface EntityContactList {
	id: number;
	entity_type: string;
	entity_id: number;
	entity: Record<string, unknown>;
	contact_id: number;
	contact: Record<string, unknown>;
	contact_attrs: Record<string, unknown>;
	is_active: boolean;
}
