// Code generated by cmd/codegen. DO NOT EDIT.

export interface EntityContactDTO {
	id: number;
	entity_type: string;
	entity_id: number;
	contact_id: number;
	is_active: boolean;
}

export interface EntityContact {
	id: number;
	entity_type: string;
	entity_id: number;
	contact_id: number;
	is_active: boolean;
}

export type EntityContactKey = Pick<
	EntityContact,
	"id"
>;
export type EntityContactNew = Pick<
	EntityContact,
	"entity_type" | "entity_id" | "contact_id" | "is_active"
>;
export type EntityContactUpd = Partial<Pick<
	EntityContact,
	"entity_type" | "entity_id" | "contact_id" | "is_active"
>>;

export interface EntityContactUpdate {
	key: EntityContactKey;
	model: EntityContactUpd;
}
