// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialListDTO {
	id: number;
	name: string;
	name_full: string | null;
	measure_unit_id: number;
	measure_unit: Record<string, unknown>;
	material_type_id: number;
	material_type: Record<string, unknown>;
	is_active: boolean;
	balances: Record<string, unknown>;
}

export interface MaterialList {
	id: number;
	name: string;
	name_full: string | null;
	measure_unit_id: number;
	measure_unit: Record<string, unknown>;
	material_type_id: number;
	material_type: Record<string, unknown>;
	is_active: boolean;
	balances: Record<string, unknown>;
}
