// Code generated by cmd/codegen. DO NOT EDIT.
import type {
	MaterialStatusType,
} from "@/types/enums/materialStatusType.gen";

export interface MaterialStatusListDTO {
	id: number;
	created_at: string;
	material_id: number;
	material: Record<string, unknown>;
	status: MaterialStatusType;
	is_active: boolean;
}

export interface MaterialStatusList {
	id: number;
	created_at: Date;
	material_id: number;
	material: Record<string, unknown>;
	status: MaterialStatusType;
	is_active: boolean;
}
