// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialConsumptionItemListDTO {
	id: number;
	line_num: number;
	material_consumption_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
}

export interface MaterialConsumptionItemList {
	id: number;
	line_num: number;
	material_consumption_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
}
