// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialRequestListDTO {
	id: number;
	date: string;
	construction_site_id: number;
	construction_manager_id: number;
	comment: string | null;
	version: number;
	construction_site: Record<string, unknown>;
	construction_manager: Record<string, unknown>;
	status_id: number;
	status: Record<string, unknown>;
}

export interface MaterialRequestList {
	id: number;
	date: Date;
	construction_site_id: number;
	construction_manager_id: number;
	comment: string | null;
	version: number;
	construction_site: Record<string, unknown>;
	construction_manager: Record<string, unknown>;
	status_id: number;
	status: Record<string, unknown>;
}
