// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialRequestStatusDTO {
	id: number;
	code: string;
	name: string;
}

export interface MaterialRequestStatus {
	id: number;
	code: string;
	name: string;
}

export type MaterialRequestStatusKey = Pick<
	MaterialRequestStatus,
	"id"
>;
export type MaterialRequestStatusUpd = Partial<Pick<
	MaterialRequestStatus,
	"name"
>>;

export interface MaterialRequestStatusUpdate {
	key: MaterialRequestStatusKey;
	model: MaterialRequestStatusUpd;
}
