// Code generated by cmd/codegen. DO NOT EDIT.
import type { MaterialStatusType } from "@/types/enums/materialStatusType.gen";

export interface MaterialStatusDTO {
	id: number;
	created_at: string;
	construction_site_id: number | null;
	material_id: number;
	status: MaterialStatusType;
	is_active: boolean;
}

export interface MaterialStatus {
	id: number;
	created_at: Date;
	construction_site_id: number | null;
	material_id: number;
	status: MaterialStatusType;
	is_active: boolean;
}

export type MaterialStatusKey = Pick<MaterialStatus, "id">;
export type MaterialStatusNew = Pick<
	MaterialStatus,
	"created_at" | "material_id" | "status" | "is_active"
> & {
	construction_site_id: number;
};
export type MaterialStatusUpd = Partial<
	Pick<
		MaterialStatus,
		"created_at" | "material_id" | "status" | "is_active"
	>
> & {
	construction_site_id?: number;
};

export interface MaterialStatusUpdate {
	key: MaterialStatusKey;
	model: MaterialStatusUpd;
}
