// Code generated by cmd/codegen. DO NOT EDIT.
import type { MaterialStatusType } from "@/types/enums/materialStatusType.gen";

export interface MaterialStatusListDTO {
	id: number;
	created_at: string;
	construction_site_id: number | null;
	construction_site: Record<string, unknown> | null;
	material_id: number;
	material: Record<string, unknown>;
	status: MaterialStatusType;
	is_active: boolean;
}

export interface MaterialStatusList {
	id: number;
	created_at: Date;
	construction_site_id: number | null;
	construction_site: Record<string, unknown> | null;
	material_id: number;
	material: Record<string, unknown>;
	status: MaterialStatusType;
	is_active: boolean;
}
