// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialReceiptListDTO {
	id: number;
	date: string;
	construction_site_id: number | null;
	supplier_id: number;
	number: string;
	comment: string | null;
	version: number;
	construction_site: Record<string, unknown> | null;
	supplier: Record<string, unknown>;
}

export interface MaterialReceiptList {
	id: number;
	date: Date;
	construction_site_id: number | null;
	supplier_id: number;
	number: string;
	comment: string | null;
	version: number;
	construction_site: Record<string, unknown> | null;
	supplier: Record<string, unknown>;
}
