// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialRequestItemDTO {
	id: number;
	line_num: number;
	material_request_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	supplier_id: number | null;
	required_date: string | null;
	order_importance_id: number;
	status_id: number;
}

export interface MaterialRequestItem {
	id: number;
	line_num: number;
	material_request_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	supplier_id: number | null;
	required_date: Date | null;
	order_importance_id: number;
	status_id: number;
}

export type MaterialRequestItemKey = Pick<
	MaterialRequestItem,
	"id"
>;
export type MaterialRequestItemNew = Pick<
	MaterialRequestItem,
	"line_num" | "material_request_id" | "material_id" | "measure_unit_id" | "quant" | "supplier_id" | "required_date" | "order_importance_id" | "status_id"
>;
export type MaterialRequestItemUpd = Partial<Pick<
	MaterialRequestItem,
	"line_num" | "material_request_id" | "material_id" | "measure_unit_id" | "quant" | "supplier_id" | "required_date" | "order_importance_id" | "status_id"
>>;

export interface MaterialRequestItemUpdate {
	key: MaterialRequestItemKey;
	model: MaterialRequestItemUpd;
}
