// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialRequestItemListDTO {
	id: number;
	line_num: number;
	material_request_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	supplier_id: number | null;
	required_date: string | null;
	order_importance_id: number;
	status_id: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
	supplier: Record<string, unknown> | null;
	order_importance: Record<string, unknown>;
	status: Record<string, unknown>;
}

export interface MaterialRequestItemList {
	id: number;
	line_num: number;
	material_request_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	supplier_id: number | null;
	required_date: Date | null;
	order_importance_id: number;
	status_id: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
	supplier: Record<string, unknown> | null;
	order_importance: Record<string, unknown>;
	status: Record<string, unknown>;
}
