// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialConsumptionDTO {
	id: number;
	date: string;
	construction_site_id: number;
	comment: string | null;
	version: number;
}

export interface MaterialConsumption {
	id: number;
	date: Date;
	construction_site_id: number;
	comment: string | null;
	version: number;
}

export type MaterialConsumptionKey = Pick<
	MaterialConsumption,
	"id"
>;
export type MaterialConsumptionNew = Pick<
	MaterialConsumption,
	"date" | "construction_site_id" | "comment"
>;
export type MaterialConsumptionUpd = Partial<Pick<
	MaterialConsumption,
	"date" | "construction_site_id" | "comment"
>>;

export interface MaterialConsumptionUpdate {
	key: MaterialConsumptionKey;
	model: MaterialConsumptionUpd;
}
