// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialReceiptDTO {
	id: number;
	date: string;
	construction_site_id: number | null;
	supplier_id: number;
	number: string;
	comment: string | null;
	version: number;
}

export interface MaterialReceipt {
	id: number;
	date: Date;
	construction_site_id: number | null;
	supplier_id: number;
	number: string;
	comment: string | null;
	version: number;
}

export type MaterialReceiptKey = Pick<
	MaterialReceipt,
	"id"
>;
export type MaterialReceiptNew = Pick<
	MaterialReceipt,
	"date" | "construction_site_id" | "supplier_id" | "number" | "comment"
>;
export type MaterialReceiptUpd = Partial<Pick<
	MaterialReceipt,
	"date" | "construction_site_id" | "supplier_id" | "number" | "comment"
>>;

export interface MaterialReceiptUpdate {
	key: MaterialReceiptKey;
	model: MaterialReceiptUpd;
}
