// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialTransferDTO {
	id: number;
	date: string;
	source_construction_site_id: number;
	destination_construction_site_id: number;
	comment: string | null;
	version: number;
}

export interface MaterialTransfer {
	id: number;
	date: Date;
	source_construction_site_id: number;
	destination_construction_site_id: number;
	comment: string | null;
	version: number;
}

export type MaterialTransferKey = Pick<
	MaterialTransfer,
	"id"
>;
export type MaterialTransferNew = Pick<
	MaterialTransfer,
	"date" | "source_construction_site_id" | "destination_construction_site_id" | "comment"
>;
export type MaterialTransferUpd = Partial<Pick<
	MaterialTransfer,
	"date" | "source_construction_site_id" | "destination_construction_site_id" | "comment"
>>;

export interface MaterialTransferUpdate {
	key: MaterialTransferKey;
	model: MaterialTransferUpd;
}
