// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialTransferItemListDTO {
	id: number;
	line_num: number;
	material_transfer_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
}

export interface MaterialTransferItemList {
	id: number;
	line_num: number;
	material_transfer_id: number;
	material_id: number;
	measure_unit_id: number;
	quant: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
}
