// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialReceiptItemListDTO {
	id: number;
	line_num: number;
	material_receipt_id: number;
	material_id: number;
	measure_unit_id: number;
	construction_site_id: number | null;
	quant: number;
	price: number;
	amount: number;
	vat_percent: number;
	vat_amount: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
	construction_site: Record<string, unknown>;
}

export interface MaterialReceiptItemList {
	id: number;
	line_num: number;
	material_receipt_id: number;
	material_id: number;
	measure_unit_id: number;
	construction_site_id: number | null;
	quant: number;
	price: number;
	amount: number;
	vat_percent: number;
	vat_amount: number;
	material: Record<string, unknown>;
	measure_unit: Record<string, unknown>;
	construction_site: Record<string, unknown>;
}
