// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaterialRequestDTO {
	id: number;
	date: string;
	construction_site_id: number;
	construction_manager_id: number;
	comment: string | null;
	version: number;
}

export interface MaterialRequest {
	id: number;
	date: Date;
	construction_site_id: number;
	construction_manager_id: number;
	comment: string | null;
	version: number;
}

export type MaterialRequestKey = Pick<MaterialRequest, "id">;
export type MaterialRequestNew = Pick<
	MaterialRequest,
	"date" | "construction_site_id" | "construction_manager_id" | "comment"
>;
export type MaterialRequestUpd = Partial<
	Pick<
		MaterialRequest,
		| "date"
		| "construction_site_id"
		| "construction_manager_id"
		| "comment"
	>
>;

export interface MaterialRequestUpdate {
	key: MaterialRequestKey;
	model: MaterialRequestUpd;
}
