// Code generated by cmd/codegen. DO NOT EDIT.
import type {
	MaterialStatusType,
} from "@/types/enums/materialStatusType.gen";

export interface MaterialStatusDTO {
	id: number;
	created_at: string;
	material_id: number;
	status: MaterialStatusType;
	is_active: boolean;
}

export interface MaterialStatus {
	id: number;
	created_at: Date;
	material_id: number;
	status: MaterialStatusType;
	is_active: boolean;
}

export type MaterialStatusKey = Pick<
	MaterialStatus,
	"id"
>;
export type MaterialStatusNew = Pick<
	MaterialStatus,
	"created_at" | "material_id" | "status" | "is_active"
>;
export type MaterialStatusUpd = Partial<Pick<
	MaterialStatus,
	"created_at" | "material_id" | "status" | "is_active"
>>;

export interface MaterialStatusUpdate {
	key: MaterialStatusKey;
	model: MaterialStatusUpd;
}
