// Code generated by cmd/codegen. DO NOT EDIT.

export interface MaxUserListDTO {
	id: number;
	contact: Record<string, unknown> | null;
	max_user_id: number;
	username: string | null;
	avatar_url: string | null;
	raw_user: Record<string, unknown>;
	is_active: boolean;
}

export interface MaxUserList {
	id: number;
	contact: Record<string, unknown> | null;
	max_user_id: number;
	username: string | null;
	avatar_url: string | null;
	raw_user: Record<string, unknown>;
	is_active: boolean;
}
