// Code generated by cmd/codegen. DO NOT EDIT.

export interface OrderImportanceDTO {
	id: number;
	name: string;
	sort_order: number;
	is_active: boolean;
}

export interface OrderImportance {
	id: number;
	name: string;
	sort_order: number;
	is_active: boolean;
}

export type OrderImportanceKey = Pick<OrderImportance, "id">;
export type OrderImportanceNew = Pick<
	OrderImportance,
	"name" | "sort_order" | "is_active"
>;
export type OrderImportanceUpd = Partial<
	Pick<OrderImportance, "name" | "sort_order" | "is_active">
>;

export interface OrderImportanceUpdate {
	key: OrderImportanceKey;
	model: OrderImportanceUpd;
}
