// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	ConstructionSite,
	ConstructionSiteNew,
	ConstructionSiteUpd,
} from "@/types/constructionSite.gen";

export type ConstructionSiteFormModel = {
	[Field in keyof ConstructionSite]?: ConstructionSite[Field] | null;
};

export const createConstructionSiteFormModel = (): ConstructionSiteFormModel => ({
	name: "",
	is_active: true,
});

export const constructionSiteFormMutationFields = [
	"name",
	"is_active",
] satisfies FormMutationFieldConfig<
	ConstructionSiteFormModel,
	ConstructionSiteNew | ConstructionSiteUpd
>[];
