// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	Contact,
	ContactNew,
	ContactUpd,
} from "@/types/contact.gen";

export type ContactFormModel = {
	[Field in keyof Contact]?: Contact[Field] | null;
};

export const createContactFormModel = (): ContactFormModel => ({
	name: "",
	phone: "",
	email: null,
	employee_post_id: null,
	is_active: true,
});

export const contactFormMutationFields = [
	"name",
	"phone",
	"email",
	"employee_post_id",
	"is_active",
] satisfies FormMutationFieldConfig<
	ContactFormModel,
	ContactNew | ContactUpd
>[];
