// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	EmployeePost,
	EmployeePostNew,
	EmployeePostUpd,
} from "@/types/employeePost.gen";

export type EmployeePostFormModel = {
	[Field in keyof EmployeePost]?: EmployeePost[Field] | null;
};

export const createEmployeePostFormModel = (): EmployeePostFormModel => ({
	name: "",
	is_active: false,
});

export const employeePostFormMutationFields = [
	"name",
	"is_active",
] satisfies FormMutationFieldConfig<
	EmployeePostFormModel,
	EmployeePostNew | EmployeePostUpd
>[];
