// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	MaterialTransfer,
	MaterialTransferNew,
	MaterialTransferUpd,
} from "@/types/materialTransfer.gen";

export type MaterialTransferFormModel = {
	[Field in keyof MaterialTransfer]?: MaterialTransfer[Field] | null;
};

export const createMaterialTransferFormModel = (): MaterialTransferFormModel => ({
	date: undefined,
	source_construction_site_id: 0,
	destination_construction_site_id: 0,
	comment: null,
});

export const materialTransferFormMutationFields = [
	"date",
	"source_construction_site_id",
	"destination_construction_site_id",
	"comment",
] satisfies FormMutationFieldConfig<
	MaterialTransferFormModel,
	MaterialTransferNew | MaterialTransferUpd
>[];
