// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	MaterialReceipt,
	MaterialReceiptNew,
	MaterialReceiptUpd,
} from "@/types/materialReceipt.gen";

export type MaterialReceiptFormModel = {
	[Field in keyof MaterialReceipt]?: MaterialReceipt[Field] | null;
};

export const createMaterialReceiptFormModel = (): MaterialReceiptFormModel => ({
	date: undefined,
	number: "",
	construction_site_id: null,
	supplier_id: 0,
	comment: null,
});

export const materialReceiptFormMutationFields = [
	"date",
	"construction_site_id",
	"supplier_id",
	"number",
	"comment",
] satisfies FormMutationFieldConfig<
	MaterialReceiptFormModel,
	MaterialReceiptNew | MaterialReceiptUpd
>[];
