// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	MaterialType,
	MaterialTypeNew,
	MaterialTypeUpd,
} from "@/types/materialType.gen";

export type MaterialTypeFormModel = {
	[Field in keyof MaterialType]?: MaterialType[Field] | null;
};

export const createMaterialTypeFormModel = (): MaterialTypeFormModel => ({
	code: "",
	name: "",
	is_active: false,
});

export const materialTypeFormMutationFields = [
	"code",
	"name",
	"is_active",
] satisfies FormMutationFieldConfig<
	MaterialTypeFormModel,
	MaterialTypeNew | MaterialTypeUpd
>[];
