// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	MaterialRequest,
	MaterialRequestNew,
	MaterialRequestUpd,
} from "@/types/materialRequest.gen";

export type MaterialRequestFormModel = {
	[Field in keyof MaterialRequest]?: MaterialRequest[Field] | null;
};

export const createMaterialRequestFormModel = (): MaterialRequestFormModel => ({
	date: undefined,
	construction_site_id: 0,
	construction_manager_id: 0,
	comment: null,
});

export const materialRequestFormMutationFields = [
	"date",
	"construction_site_id",
	"construction_manager_id",
	"comment",
] satisfies FormMutationFieldConfig<
	MaterialRequestFormModel,
	MaterialRequestNew | MaterialRequestUpd
>[];
