// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	MaterialConsumption,
	MaterialConsumptionNew,
	MaterialConsumptionUpd,
} from "@/types/materialConsumption.gen";

export type MaterialConsumptionFormModel = {
	[Field in keyof MaterialConsumption]?: MaterialConsumption[Field] | null;
};

export const createMaterialConsumptionFormModel = (): MaterialConsumptionFormModel => ({
	date: undefined,
	construction_site_id: 0,
	comment: null,
});

export const materialConsumptionFormMutationFields = [
	"date",
	"construction_site_id",
	"comment",
] satisfies FormMutationFieldConfig<
	MaterialConsumptionFormModel,
	MaterialConsumptionNew | MaterialConsumptionUpd
>[];
