// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	Material,
	MaterialNew,
	MaterialUpd,
} from "@/types/material.gen";

export type MaterialFormModel = {
	[Field in keyof Material]?: Material[Field] | null;
};

export const createMaterialFormModel = (): MaterialFormModel => ({
	material_type_id: 0,
	name: "",
	name_full: null,
	measure_unit_id: 0,
	is_active: true,
});

export const materialFormMutationFields = [
	"name",
	"name_full",
	"measure_unit_id",
	"material_type_id",
	"is_active",
] satisfies FormMutationFieldConfig<
	MaterialFormModel,
	MaterialNew | MaterialUpd
>[];
