// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	MeasureUnit,
	MeasureUnitNew,
	MeasureUnitUpd,
} from "@/types/measureUnit.gen";

export type MeasureUnitFormModel = {
	[Field in keyof MeasureUnit]?: MeasureUnit[Field] | null;
};

export const createMeasureUnitFormModel = (): MeasureUnitFormModel => ({
	name: "",
	name_full: "",
	okei_code: "",
	is_active: true,
});

export const measureUnitFormMutationFields = [
	"name",
	"name_full",
	"okei_code",
	"is_active",
] satisfies FormMutationFieldConfig<
	MeasureUnitFormModel,
	MeasureUnitNew | MeasureUnitUpd
>[];
