// Code generated by cmd/codegen. DO NOT EDIT.

import type { FormMutationFieldConfig } from "@katren/vue-collection-lib";

import type {
	Supplier,
	SupplierNew,
	SupplierUpd,
} from "@/types/supplier.gen";

export type SupplierFormModel = {
	[Field in keyof Supplier]?: Supplier[Field] | null;
};

export const createSupplierFormModel = (): SupplierFormModel => ({
	name: "",
	name_full: "",
	inn: "",
	kpp: null,
	is_active: true,
});

export const supplierFormMutationFields = [
	"name",
	"name_full",
	"inn",
	"kpp",
	"is_active",
] satisfies FormMutationFieldConfig<
	SupplierFormModel,
	SupplierNew | SupplierUpd
>[];
