// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type ConstructionSite,
	type ConstructionSiteDTO,
	type ConstructionSiteKey,
	type ConstructionSiteNew,
	type ConstructionSiteUpd,
} from "@/types/constructionSite.gen";
import { constructionSiteFromDTO } from "@/schemas/constructionSite.gen";

const basePath = "/construction-sites";

const constructionSiteCrudApi = createCrudApi<
	ConstructionSite,
	ConstructionSiteDTO,
	ConstructionSite,
	ConstructionSiteDTO,
	ConstructionSiteKey,
	ConstructionSiteNew,
	ConstructionSiteUpd
>({
	basePath,
	serviceName: "ConstructionSite",
	getKeyValue: (key: ConstructionSiteKey): number => {
		return key.id;
	},
	fromListDTO: constructionSiteFromDTO,
	fromDetailDTO: constructionSiteFromDTO,
});

export const constructionSiteApi = {
	...constructionSiteCrudApi,
};
