// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type Contact,
	type ContactDTO,
	type ContactKey,
	type ContactNew,
	type ContactUpd,
} from "@/types/contact.gen";
import { contactFromDTO } from "@/schemas/contact.gen";

const basePath = "/contacts";

const contactCrudApi = createCrudApi<
	Contact,
	ContactDTO,
	Contact,
	ContactDTO,
	ContactKey,
	ContactNew,
	ContactUpd
>({
	basePath,
	serviceName: "Contact",
	getKeyValue: (key: ContactKey): number => {
		return key.id;
	},
	fromListDTO: contactFromDTO,
	fromDetailDTO: contactFromDTO,
});

export const contactApi = {
	...contactCrudApi,
};
