// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type EmployeePost,
	type EmployeePostDTO,
	type EmployeePostKey,
	type EmployeePostNew,
	type EmployeePostUpd,
} from "@/types/employeePost.gen";
import { employeePostFromDTO } from "@/schemas/employeePost.gen";

const basePath = "/employee-post";

const employeePostCrudApi = createCrudApi<
	EmployeePost,
	EmployeePostDTO,
	EmployeePost,
	EmployeePostDTO,
	EmployeePostKey,
	EmployeePostNew,
	EmployeePostUpd
>({
	basePath,
	serviceName: "EmployeePost",
	getKeyValue: (key: EmployeePostKey): number => {
		return key.id;
	},
	fromListDTO: employeePostFromDTO,
	fromDetailDTO: employeePostFromDTO,
});

export const employeePostApi = {
	...employeePostCrudApi,
};
