// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	EntityContactList,
	EntityContactListDTO,
} from "@/types/entityContactList.gen";
import { entityContactListFromDTO } from "@/schemas/entityContactList.gen";
import {
	type EntityContact,
	type EntityContactDTO,
	type EntityContactKey,
	type EntityContactNew,
	type EntityContactUpd,
} from "@/types/entityContact.gen";
import { entityContactFromDTO } from "@/schemas/entityContact.gen";

const basePath = "/entity-contacts";

const entityContactCrudApi = createCrudApi<
	EntityContactList,
	EntityContactListDTO,
	EntityContact,
	EntityContactDTO,
	EntityContactKey,
	EntityContactNew,
	EntityContactUpd
>({
	basePath,
	serviceName: "EntityContact",
	getKeyValue: (key: EntityContactKey): number => {
		return key.id;
	},
	fromListDTO: entityContactListFromDTO,
	fromDetailDTO: entityContactFromDTO,
});

export const entityContactApi = {
	...entityContactCrudApi,
};
