// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialRequestItemList,
	MaterialRequestItemListDTO,
} from "@/types/materialRequestItemList.gen";
import { materialRequestItemListFromDTO } from "@/schemas/materialRequestItemList.gen";
import {
	type MaterialRequestItem,
	type MaterialRequestItemDTO,
	type MaterialRequestItemKey,
	type MaterialRequestItemNew,
	type MaterialRequestItemUpd,
} from "@/types/materialRequestItem.gen";
import { materialRequestItemFromDTO } from "@/schemas/materialRequestItem.gen";

const basePath = "/material-request-items";

const materialRequestItemCrudApi = createCrudApi<
	MaterialRequestItemList,
	MaterialRequestItemListDTO,
	MaterialRequestItem,
	MaterialRequestItemDTO,
	MaterialRequestItemKey,
	MaterialRequestItemNew,
	MaterialRequestItemUpd
>({
	basePath,
	serviceName: "MaterialRequestItem",
	getKeyValue: (key: MaterialRequestItemKey): number => {
		return key.id;
	},
	fromListDTO: materialRequestItemListFromDTO,
	fromDetailDTO: materialRequestItemFromDTO,
});

export const materialRequestItemApi = {
	...materialRequestItemCrudApi,
};
