// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialList,
	MaterialListDTO,
} from "@/types/materialList.gen";
import { materialListFromDTO } from "@/schemas/materialList.gen";
import {
	type Material,
	type MaterialDTO,
	type MaterialKey,
	type MaterialNew,
	type MaterialUpd,
} from "@/types/material.gen";
import { materialFromDTO } from "@/schemas/material.gen";

const basePath = "/material";

const materialCrudApi = createCrudApi<
	MaterialList,
	MaterialListDTO,
	Material,
	MaterialDTO,
	MaterialKey,
	MaterialNew,
	MaterialUpd
>({
	basePath,
	serviceName: "Material",
	getKeyValue: (key: MaterialKey): number => {
		return key.id;
	},
	fromListDTO: materialListFromDTO,
	fromDetailDTO: materialFromDTO,
});

export const materialApi = {
	...materialCrudApi,
};
