// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialReceiptItemList,
	MaterialReceiptItemListDTO,
} from "@/types/materialReceiptItemList.gen";
import { materialReceiptItemListFromDTO } from "@/schemas/materialReceiptItemList.gen";
import {
	type MaterialReceiptItem,
	type MaterialReceiptItemDTO,
	type MaterialReceiptItemKey,
	type MaterialReceiptItemNew,
	type MaterialReceiptItemUpd,
} from "@/types/materialReceiptItem.gen";
import { materialReceiptItemFromDTO } from "@/schemas/materialReceiptItem.gen";

const basePath = "/material-receipt-items";

const materialReceiptItemCrudApi = createCrudApi<
	MaterialReceiptItemList,
	MaterialReceiptItemListDTO,
	MaterialReceiptItem,
	MaterialReceiptItemDTO,
	MaterialReceiptItemKey,
	MaterialReceiptItemNew,
	MaterialReceiptItemUpd
>({
	basePath,
	serviceName: "MaterialReceiptItem",
	getKeyValue: (key: MaterialReceiptItemKey): number => {
		return key.id;
	},
	fromListDTO: materialReceiptItemListFromDTO,
	fromDetailDTO: materialReceiptItemFromDTO,
});

export const materialReceiptItemApi = {
	...materialReceiptItemCrudApi,
};
