// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialTransferList,
	MaterialTransferListDTO,
} from "@/types/materialTransferList.gen";
import { materialTransferListFromDTO } from "@/schemas/materialTransferList.gen";
import {
	type MaterialTransfer,
	type MaterialTransferDTO,
	type MaterialTransferKey,
	type MaterialTransferNew,
	type MaterialTransferUpd,
} from "@/types/materialTransfer.gen";
import { materialTransferFromDTO } from "@/schemas/materialTransfer.gen";

const basePath = "/material-transfers";

const materialTransferCrudApi = createCrudApi<
	MaterialTransferList,
	MaterialTransferListDTO,
	MaterialTransfer,
	MaterialTransferDTO,
	MaterialTransferKey,
	MaterialTransferNew,
	MaterialTransferUpd
>({
	basePath,
	serviceName: "MaterialTransfer",
	getKeyValue: (key: MaterialTransferKey): number => {
		return key.id;
	},
	fromListDTO: materialTransferListFromDTO,
	fromDetailDTO: materialTransferFromDTO,
});

export const materialTransferApi = {
	...materialTransferCrudApi,
};
