// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialConsumptionList,
	MaterialConsumptionListDTO,
} from "@/types/materialConsumptionList.gen";
import { materialConsumptionListFromDTO } from "@/schemas/materialConsumptionList.gen";
import {
	type MaterialConsumption,
	type MaterialConsumptionDTO,
	type MaterialConsumptionKey,
	type MaterialConsumptionNew,
	type MaterialConsumptionUpd,
} from "@/types/materialConsumption.gen";
import { materialConsumptionFromDTO } from "@/schemas/materialConsumption.gen";

const basePath = "/material-consumptions";

const materialConsumptionCrudApi = createCrudApi<
	MaterialConsumptionList,
	MaterialConsumptionListDTO,
	MaterialConsumption,
	MaterialConsumptionDTO,
	MaterialConsumptionKey,
	MaterialConsumptionNew,
	MaterialConsumptionUpd
>({
	basePath,
	serviceName: "MaterialConsumption",
	getKeyValue: (key: MaterialConsumptionKey): number => {
		return key.id;
	},
	fromListDTO: materialConsumptionListFromDTO,
	fromDetailDTO: materialConsumptionFromDTO,
});

export const materialConsumptionApi = {
	...materialConsumptionCrudApi,
};
