// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type MaterialType,
	type MaterialTypeDTO,
	type MaterialTypeKey,
	type MaterialTypeNew,
	type MaterialTypeUpd,
} from "@/types/materialType.gen";
import { materialTypeFromDTO } from "@/schemas/materialType.gen";

const basePath = "/material-types";

const materialTypeCrudApi = createCrudApi<
	MaterialType,
	MaterialTypeDTO,
	MaterialType,
	MaterialTypeDTO,
	MaterialTypeKey,
	MaterialTypeNew,
	MaterialTypeUpd
>({
	basePath,
	serviceName: "MaterialType",
	getKeyValue: (key: MaterialTypeKey): number => {
		return key.id;
	},
	fromListDTO: materialTypeFromDTO,
	fromDetailDTO: materialTypeFromDTO,
});

export const materialTypeApi = {
	...materialTypeCrudApi,
};
