// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialConsumptionItemList,
	MaterialConsumptionItemListDTO,
} from "@/types/materialConsumptionItemList.gen";
import { materialConsumptionItemListFromDTO } from "@/schemas/materialConsumptionItemList.gen";
import {
	type MaterialConsumptionItem,
	type MaterialConsumptionItemDTO,
	type MaterialConsumptionItemKey,
	type MaterialConsumptionItemNew,
	type MaterialConsumptionItemUpd,
} from "@/types/materialConsumptionItem.gen";
import { materialConsumptionItemFromDTO } from "@/schemas/materialConsumptionItem.gen";

const basePath = "/material-consumption-items";

const materialConsumptionItemCrudApi = createCrudApi<
	MaterialConsumptionItemList,
	MaterialConsumptionItemListDTO,
	MaterialConsumptionItem,
	MaterialConsumptionItemDTO,
	MaterialConsumptionItemKey,
	MaterialConsumptionItemNew,
	MaterialConsumptionItemUpd
>({
	basePath,
	serviceName: "MaterialConsumptionItem",
	getKeyValue: (key: MaterialConsumptionItemKey): number => {
		return key.id;
	},
	fromListDTO: materialConsumptionItemListFromDTO,
	fromDetailDTO: materialConsumptionItemFromDTO,
});

export const materialConsumptionItemApi = {
	...materialConsumptionItemCrudApi,
};
