// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialTransferItemList,
	MaterialTransferItemListDTO,
} from "@/types/materialTransferItemList.gen";
import { materialTransferItemListFromDTO } from "@/schemas/materialTransferItemList.gen";
import {
	type MaterialTransferItem,
	type MaterialTransferItemDTO,
	type MaterialTransferItemKey,
	type MaterialTransferItemNew,
	type MaterialTransferItemUpd,
} from "@/types/materialTransferItem.gen";
import { materialTransferItemFromDTO } from "@/schemas/materialTransferItem.gen";

const basePath = "/material-transfer-items";

const materialTransferItemCrudApi = createCrudApi<
	MaterialTransferItemList,
	MaterialTransferItemListDTO,
	MaterialTransferItem,
	MaterialTransferItemDTO,
	MaterialTransferItemKey,
	MaterialTransferItemNew,
	MaterialTransferItemUpd
>({
	basePath,
	serviceName: "MaterialTransferItem",
	getKeyValue: (key: MaterialTransferItemKey): number => {
		return key.id;
	},
	fromListDTO: materialTransferItemListFromDTO,
	fromDetailDTO: materialTransferItemFromDTO,
});

export const materialTransferItemApi = {
	...materialTransferItemCrudApi,
};
