// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type MaterialRequestStatus,
	type MaterialRequestStatusDTO,
	type MaterialRequestStatusKey,
	type MaterialRequestStatusUpd,
} from "@/types/materialRequestStatus.gen";
import { materialRequestStatusFromDTO } from "@/schemas/materialRequestStatus.gen";

const basePath = "/material-request-statuses";

const materialRequestStatusCrudApi = createCrudApi<
	MaterialRequestStatus,
	MaterialRequestStatusDTO,
	MaterialRequestStatus,
	MaterialRequestStatusDTO,
	MaterialRequestStatusKey,
	never,
	MaterialRequestStatusUpd
>({
	basePath,
	serviceName: "MaterialRequestStatus",
	getKeyValue: (key: MaterialRequestStatusKey): number => {
		return key.id;
	},
	fromListDTO: materialRequestStatusFromDTO,
	fromDetailDTO: materialRequestStatusFromDTO,
});

export const materialRequestStatusApi = {
	...materialRequestStatusCrudApi,
};
