// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialStatusList,
	MaterialStatusListDTO,
} from "@/types/materialStatusList.gen";
import { materialStatusListFromDTO } from "@/schemas/materialStatusList.gen";
import {
	type MaterialStatus,
	type MaterialStatusDTO,
	type MaterialStatusKey,
	type MaterialStatusNew,
	type MaterialStatusUpd,
} from "@/types/materialStatus.gen";
import { materialStatusFromDTO } from "@/schemas/materialStatus.gen";

const basePath = "/material-statuses";

const materialStatusCrudApi = createCrudApi<
	MaterialStatusList,
	MaterialStatusListDTO,
	MaterialStatus,
	MaterialStatusDTO,
	MaterialStatusKey,
	MaterialStatusNew,
	MaterialStatusUpd
>({
	basePath,
	serviceName: "MaterialStatus",
	getKeyValue: (key: MaterialStatusKey): number => {
		return key.id;
	},
	fromListDTO: materialStatusListFromDTO,
	fromDetailDTO: materialStatusFromDTO,
});

export const materialStatusApi = {
	...materialStatusCrudApi,
};
