// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialReceiptList,
	MaterialReceiptListDTO,
} from "@/types/materialReceiptList.gen";
import { materialReceiptListFromDTO } from "@/schemas/materialReceiptList.gen";
import {
	type MaterialReceipt,
	type MaterialReceiptDTO,
	type MaterialReceiptKey,
	type MaterialReceiptNew,
	type MaterialReceiptUpd,
} from "@/types/materialReceipt.gen";
import { materialReceiptFromDTO } from "@/schemas/materialReceipt.gen";

const basePath = "/material-receipts";

const materialReceiptCrudApi = createCrudApi<
	MaterialReceiptList,
	MaterialReceiptListDTO,
	MaterialReceipt,
	MaterialReceiptDTO,
	MaterialReceiptKey,
	MaterialReceiptNew,
	MaterialReceiptUpd
>({
	basePath,
	serviceName: "MaterialReceipt",
	getKeyValue: (key: MaterialReceiptKey): number => {
		return key.id;
	},
	fromListDTO: materialReceiptListFromDTO,
	fromDetailDTO: materialReceiptFromDTO,
});

export const materialReceiptApi = {
	...materialReceiptCrudApi,
};
