// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaterialRequestList,
	MaterialRequestListDTO,
} from "@/types/materialRequestList.gen";
import { materialRequestListFromDTO } from "@/schemas/materialRequestList.gen";
import {
	type MaterialRequest,
	type MaterialRequestDTO,
	type MaterialRequestKey,
	type MaterialRequestNew,
	type MaterialRequestUpd,
} from "@/types/materialRequest.gen";
import { materialRequestFromDTO } from "@/schemas/materialRequest.gen";

const basePath = "/material-requests";

const materialRequestCrudApi = createCrudApi<
	MaterialRequestList,
	MaterialRequestListDTO,
	MaterialRequest,
	MaterialRequestDTO,
	MaterialRequestKey,
	MaterialRequestNew,
	MaterialRequestUpd
>({
	basePath,
	serviceName: "MaterialRequest",
	getKeyValue: (key: MaterialRequestKey): number => {
		return key.id;
	},
	fromListDTO: materialRequestListFromDTO,
	fromDetailDTO: materialRequestFromDTO,
});

export const materialRequestApi = {
	...materialRequestCrudApi,
};
