// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import type {
	MaxUserList,
	MaxUserListDTO,
} from "@/types/maxUserList.gen";
import { maxUserListFromDTO } from "@/schemas/maxUserList.gen";
import {
	type MaxUser,
	type MaxUserDTO,
	type MaxUserKey,
	type MaxUserUpd,
} from "@/types/maxUser.gen";
import { maxUserFromDTO } from "@/schemas/maxUser.gen";

const basePath = "/max-users";

const maxUserCrudApi = createCrudApi<
	MaxUserList,
	MaxUserListDTO,
	MaxUser,
	MaxUserDTO,
	MaxUserKey,
	never,
	MaxUserUpd
>({
	basePath,
	serviceName: "MaxUser",
	getKeyValue: (key: MaxUserKey): number => {
		return key.id;
	},
	fromListDTO: maxUserListFromDTO,
	fromDetailDTO: maxUserFromDTO,
});

export const maxUserApi = {
	...maxUserCrudApi,
};
