// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type MeasureUnit,
	type MeasureUnitDTO,
	type MeasureUnitKey,
	type MeasureUnitNew,
	type MeasureUnitUpd,
} from "@/types/measureUnit.gen";
import { measureUnitFromDTO } from "@/schemas/measureUnit.gen";

const basePath = "/measure-unit";

const measureUnitCrudApi = createCrudApi<
	MeasureUnit,
	MeasureUnitDTO,
	MeasureUnit,
	MeasureUnitDTO,
	MeasureUnitKey,
	MeasureUnitNew,
	MeasureUnitUpd
>({
	basePath,
	serviceName: "MeasureUnit",
	getKeyValue: (key: MeasureUnitKey): number => {
		return key.id;
	},
	fromListDTO: measureUnitFromDTO,
	fromDetailDTO: measureUnitFromDTO,
});

export const measureUnitApi = {
	...measureUnitCrudApi,
};
