// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type NotificationTemplate,
	type NotificationTemplateDTO,
	type NotificationTemplateKey,
	type NotificationTemplateNew,
	type NotificationTemplateUpd,
} from "@/types/notificationTemplate.gen";
import { notificationTemplateFromDTO } from "@/schemas/notificationTemplate.gen";

const basePath = "/notification-template";

const notificationTemplateCrudApi = createCrudApi<
	NotificationTemplate,
	NotificationTemplateDTO,
	NotificationTemplate,
	NotificationTemplateDTO,
	NotificationTemplateKey,
	NotificationTemplateNew,
	NotificationTemplateUpd
>({
	basePath,
	serviceName: "NotificationTemplate",
	getKeyValue: (key: NotificationTemplateKey): number => {
		return key.id;
	},
	fromListDTO: notificationTemplateFromDTO,
	fromDetailDTO: notificationTemplateFromDTO,
});

export const notificationTemplateApi = {
	...notificationTemplateCrudApi,
};
