// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type OrderImportance,
	type OrderImportanceDTO,
	type OrderImportanceKey,
	type OrderImportanceNew,
	type OrderImportanceUpd,
} from "@/types/orderImportance.gen";
import { orderImportanceFromDTO } from "@/schemas/orderImportance.gen";

const basePath = "/order-importances";

const orderImportanceCrudApi = createCrudApi<
	OrderImportance,
	OrderImportanceDTO,
	OrderImportance,
	OrderImportanceDTO,
	OrderImportanceKey,
	OrderImportanceNew,
	OrderImportanceUpd
>({
	basePath,
	serviceName: "OrderImportance",
	getKeyValue: (key: OrderImportanceKey): number => {
		return key.id;
	},
	fromListDTO: orderImportanceFromDTO,
	fromDetailDTO: orderImportanceFromDTO,
});

export const orderImportanceApi = {
	...orderImportanceCrudApi,
};
