// Code generated by cmd/codegen. DO NOT EDIT.
import { createCrudApi } from "@/api/createCrudApi";
import {
	type Supplier,
	type SupplierDTO,
	type SupplierKey,
	type SupplierNew,
	type SupplierUpd,
} from "@/types/supplier.gen";
import { supplierFromDTO } from "@/schemas/supplier.gen";

const basePath = "/supplier";

const supplierCrudApi = createCrudApi<
	Supplier,
	SupplierDTO,
	Supplier,
	SupplierDTO,
	SupplierKey,
	SupplierNew,
	SupplierUpd
>({
	basePath,
	serviceName: "Supplier",
	getKeyValue: (key: SupplierKey): number => {
		return key.id;
	},
	fromListDTO: supplierFromDTO,
	fromDetailDTO: supplierFromDTO,
});

export const supplierApi = {
	...supplierCrudApi,
};
