// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { ConstructionSite } from "@/types/constructionSite.gen";

export const createConstructionSiteSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const ConstructionSiteDTOSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		is_active: v.boolean(),
	});

	const ConstructionSiteSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		is_active: v.boolean(),
	});

	const ConstructionSiteKeySchema = v.pick(
		ConstructionSiteSchema,
		[
			"id",
		],
	);
	const ConstructionSiteNewSchema = v.pick(
		ConstructionSiteSchema,
		[
			"name",
			"is_active",
		],
	);
	const ConstructionSiteUpdSchema = v.partial(v.pick(
		ConstructionSiteSchema,
		[
			"name",
			"is_active",
		],
	));

	const ConstructionSiteUpdateSchema = v.object({
		key: ConstructionSiteKeySchema,
		model: ConstructionSiteUpdSchema,
	});
	return {
		ConstructionSiteDTOSchema,
		ConstructionSiteSchema,
		ConstructionSiteKeySchema,
		ConstructionSiteNewSchema,
		ConstructionSiteUpdSchema,
		ConstructionSiteUpdateSchema,
	};
};

const constructionSiteSchemas = createConstructionSiteSchemas(defaultTranslate);

export const ConstructionSiteDTOSchema = constructionSiteSchemas.ConstructionSiteDTOSchema;
export const ConstructionSiteSchema = constructionSiteSchemas.ConstructionSiteSchema;
export const ConstructionSiteKeySchema = constructionSiteSchemas.ConstructionSiteKeySchema;
export const ConstructionSiteNewSchema = constructionSiteSchemas.ConstructionSiteNewSchema;
export const ConstructionSiteUpdSchema = constructionSiteSchemas.ConstructionSiteUpdSchema;
export const ConstructionSiteUpdateSchema = constructionSiteSchemas.ConstructionSiteUpdateSchema;

export const constructionSiteFromDTO = (
	dto: unknown,
): ConstructionSite => {
	const parsedDTO = v.parse(ConstructionSiteDTOSchema, dto);

	return v.parse(ConstructionSiteSchema, {
		...parsedDTO,
	});
};
