// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { Contact } from "@/types/contact.gen";

export const createContactSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		StringSchema,
		TextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const ContactDTOSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		phone: StringSchema,
		email: v.nullable(StringSchema),
		employee_post_id: v.nullable(IdSchema),
		is_active: v.boolean(),
		search: v.nullable(TextSchema),
	});

	const ContactSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		phone: StringSchema,
		email: v.nullable(StringSchema),
		employee_post_id: v.nullable(IdSchema),
		is_active: v.boolean(),
		search: v.nullable(TextSchema),
	});

	const ContactKeySchema = v.pick(
		ContactSchema,
		[
			"id",
		],
	);
	const ContactNewSchema = v.pick(
		ContactSchema,
		[
			"name",
			"phone",
			"email",
			"employee_post_id",
			"is_active",
		],
	);
	const ContactUpdSchema = v.partial(v.pick(
		ContactSchema,
		[
			"name",
			"phone",
			"email",
			"employee_post_id",
			"is_active",
		],
	));

	const ContactUpdateSchema = v.object({
		key: ContactKeySchema,
		model: ContactUpdSchema,
	});
	return {
		ContactDTOSchema,
		ContactSchema,
		ContactKeySchema,
		ContactNewSchema,
		ContactUpdSchema,
		ContactUpdateSchema,
	};
};

const contactSchemas = createContactSchemas(defaultTranslate);

export const ContactDTOSchema = contactSchemas.ContactDTOSchema;
export const ContactSchema = contactSchemas.ContactSchema;
export const ContactKeySchema = contactSchemas.ContactKeySchema;
export const ContactNewSchema = contactSchemas.ContactNewSchema;
export const ContactUpdSchema = contactSchemas.ContactUpdSchema;
export const ContactUpdateSchema = contactSchemas.ContactUpdateSchema;

export const contactFromDTO = (
	dto: unknown,
): Contact => {
	const parsedDTO = v.parse(ContactDTOSchema, dto);

	return v.parse(ContactSchema, {
		...parsedDTO,
	});
};
