// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { EmployeePost } from "@/types/employeePost.gen";

export const createEmployeePostSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const EmployeePostDTOSchema = v.object({
		id: IdSchema,
		name: RequiredTextSchema,
		is_active: v.boolean(),
	});

	const EmployeePostSchema = v.object({
		id: IdSchema,
		name: RequiredTextSchema,
		is_active: v.boolean(),
	});

	const EmployeePostKeySchema = v.pick(
		EmployeePostSchema,
		[
			"id",
		],
	);
	const EmployeePostNewSchema = v.pick(
		EmployeePostSchema,
		[
			"name",
			"is_active",
		],
	);
	const EmployeePostUpdSchema = v.partial(v.pick(
		EmployeePostSchema,
		[
			"name",
			"is_active",
		],
	));

	const EmployeePostUpdateSchema = v.object({
		key: EmployeePostKeySchema,
		model: EmployeePostUpdSchema,
	});
	return {
		EmployeePostDTOSchema,
		EmployeePostSchema,
		EmployeePostKeySchema,
		EmployeePostNewSchema,
		EmployeePostUpdSchema,
		EmployeePostUpdateSchema,
	};
};

const employeePostSchemas = createEmployeePostSchemas(defaultTranslate);

export const EmployeePostDTOSchema = employeePostSchemas.EmployeePostDTOSchema;
export const EmployeePostSchema = employeePostSchemas.EmployeePostSchema;
export const EmployeePostKeySchema = employeePostSchemas.EmployeePostKeySchema;
export const EmployeePostNewSchema = employeePostSchemas.EmployeePostNewSchema;
export const EmployeePostUpdSchema = employeePostSchemas.EmployeePostUpdSchema;
export const EmployeePostUpdateSchema = employeePostSchemas.EmployeePostUpdateSchema;

export const employeePostFromDTO = (
	dto: unknown,
): EmployeePost => {
	const parsedDTO = v.parse(EmployeePostDTOSchema, dto);

	return v.parse(EmployeePostSchema, {
		...parsedDTO,
	});
};
