// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { EntityContactList } from "@/types/entityContactList.gen";

export const createEntityContactListSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const EntityContactListDTOSchema = v.object({
		id: IdSchema,
		entity_type: RequiredStringSchema,
		entity_id: IdSchema,
		entity: AttrsSchema,
		contact_id: IdSchema,
		contact: AttrsSchema,
		contact_attrs: AttrsSchema,
		is_active: v.boolean(),
	});

	const EntityContactListSchema = v.object({
		id: IdSchema,
		entity_type: RequiredStringSchema,
		entity_id: IdSchema,
		entity: AttrsSchema,
		contact_id: IdSchema,
		contact: AttrsSchema,
		contact_attrs: AttrsSchema,
		is_active: v.boolean(),
	});

	return {
		EntityContactListDTOSchema,
		EntityContactListSchema,
	};
};

const entityContactListSchemas = createEntityContactListSchemas(defaultTranslate);

export const EntityContactListDTOSchema = entityContactListSchemas.EntityContactListDTOSchema;
export const EntityContactListSchema = entityContactListSchemas.EntityContactListSchema;

export const entityContactListFromDTO = (
	dto: unknown,
): EntityContactList => {
	const parsedDTO = v.parse(EntityContactListDTOSchema, dto);

	return v.parse(EntityContactListSchema, {
		...parsedDTO,
	});
};
