// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { EntityContact } from "@/types/entityContact.gen";

export const createEntityContactSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const EntityContactDTOSchema = v.object({
		id: IdSchema,
		entity_type: RequiredStringSchema,
		entity_id: IdSchema,
		contact_id: IdSchema,
		is_active: v.boolean(),
	});

	const EntityContactSchema = v.object({
		id: IdSchema,
		entity_type: RequiredStringSchema,
		entity_id: IdSchema,
		contact_id: IdSchema,
		is_active: v.boolean(),
	});

	const EntityContactKeySchema = v.pick(
		EntityContactSchema,
		[
			"id",
		],
	);
	const EntityContactNewSchema = v.pick(
		EntityContactSchema,
		[
			"entity_type",
			"entity_id",
			"contact_id",
			"is_active",
		],
	);
	const EntityContactUpdSchema = v.partial(v.pick(
		EntityContactSchema,
		[
			"entity_type",
			"entity_id",
			"contact_id",
			"is_active",
		],
	));

	const EntityContactUpdateSchema = v.object({
		key: EntityContactKeySchema,
		model: EntityContactUpdSchema,
	});
	return {
		EntityContactDTOSchema,
		EntityContactSchema,
		EntityContactKeySchema,
		EntityContactNewSchema,
		EntityContactUpdSchema,
		EntityContactUpdateSchema,
	};
};

const entityContactSchemas = createEntityContactSchemas(defaultTranslate);

export const EntityContactDTOSchema = entityContactSchemas.EntityContactDTOSchema;
export const EntityContactSchema = entityContactSchemas.EntityContactSchema;
export const EntityContactKeySchema = entityContactSchemas.EntityContactKeySchema;
export const EntityContactNewSchema = entityContactSchemas.EntityContactNewSchema;
export const EntityContactUpdSchema = entityContactSchemas.EntityContactUpdSchema;
export const EntityContactUpdateSchema = entityContactSchemas.EntityContactUpdateSchema;

export const entityContactFromDTO = (
	dto: unknown,
): EntityContact => {
	const parsedDTO = v.parse(EntityContactDTOSchema, dto);

	return v.parse(EntityContactSchema, {
		...parsedDTO,
	});
};
