// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialTransfer } from "@/types/materialTransfer.gen";

export const createMaterialTransferSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const MaterialTransferDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		source_construction_site_id: IdSchema,
		destination_construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
	});

	const MaterialTransferSchema = v.object({
		id: IdSchema,
		date: v.date(),
		source_construction_site_id: IdSchema,
		destination_construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
	});

	const MaterialTransferKeySchema = v.pick(
		MaterialTransferSchema,
		[
			"id",
		],
	);
	const MaterialTransferNewSchema = v.pick(
		MaterialTransferSchema,
		[
			"date",
			"source_construction_site_id",
			"destination_construction_site_id",
			"comment",
		],
	);
	const MaterialTransferUpdSchema = v.partial(v.pick(
		MaterialTransferSchema,
		[
			"date",
			"source_construction_site_id",
			"destination_construction_site_id",
			"comment",
		],
	));

	const MaterialTransferUpdateSchema = v.object({
		key: MaterialTransferKeySchema,
		model: MaterialTransferUpdSchema,
	});
	return {
		MaterialTransferDTOSchema,
		MaterialTransferSchema,
		MaterialTransferKeySchema,
		MaterialTransferNewSchema,
		MaterialTransferUpdSchema,
		MaterialTransferUpdateSchema,
	};
};

const materialTransferSchemas = createMaterialTransferSchemas(defaultTranslate);

export const MaterialTransferDTOSchema = materialTransferSchemas.MaterialTransferDTOSchema;
export const MaterialTransferSchema = materialTransferSchemas.MaterialTransferSchema;
export const MaterialTransferKeySchema = materialTransferSchemas.MaterialTransferKeySchema;
export const MaterialTransferNewSchema = materialTransferSchemas.MaterialTransferNewSchema;
export const MaterialTransferUpdSchema = materialTransferSchemas.MaterialTransferUpdSchema;
export const MaterialTransferUpdateSchema = materialTransferSchemas.MaterialTransferUpdateSchema;

export const materialTransferFromDTO = (
	dto: unknown,
): MaterialTransfer => {
	const parsedDTO = v.parse(MaterialTransferDTOSchema, dto);

	return v.parse(MaterialTransferSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
