// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import {
	createMaterialStatusTypeSchemas,
} from "@/schemas/enums/materialStatusType.gen";
import type { MaterialStatus } from "@/types/materialStatus.gen";

export const createMaterialStatusSchemas = (t: TranslateFn) => {
	const {
		DateStringSchema,
		IdSchema,
	} = createCommonSchemas(t);
	const { MaterialStatusTypeSchema } = createMaterialStatusTypeSchemas(t);

	const MaterialStatusDTOSchema = v.object({
		id: IdSchema,
		created_at: DateStringSchema,
		material_id: IdSchema,
		construction_site_id: v.nullable(IdSchema),
		status: MaterialStatusTypeSchema,
		is_active: v.boolean(),
	});

	const MaterialStatusSchema = v.object({
		id: IdSchema,
		created_at: v.date(),
		material_id: IdSchema,
		construction_site_id: v.nullable(IdSchema),
		status: MaterialStatusTypeSchema,
		is_active: v.boolean(),
	});

	const MaterialStatusKeySchema = v.pick(
		MaterialStatusSchema,
		[
			"id",
		],
	);
	const MaterialStatusNewSchema = v.pick(
		MaterialStatusSchema,
		[
			"created_at",
			"material_id",
			"construction_site_id",
			"status",
			"is_active",
		],
	);
	const MaterialStatusUpdSchema = v.partial(v.pick(
		MaterialStatusSchema,
		[
			"created_at",
			"material_id",
			"construction_site_id",
			"status",
			"is_active",
		],
	));

	const MaterialStatusUpdateSchema = v.object({
		key: MaterialStatusKeySchema,
		model: MaterialStatusUpdSchema,
	});
	return {
		MaterialStatusDTOSchema,
		MaterialStatusSchema,
		MaterialStatusKeySchema,
		MaterialStatusNewSchema,
		MaterialStatusUpdSchema,
		MaterialStatusUpdateSchema,
	};
};

const materialStatusSchemas = createMaterialStatusSchemas(defaultTranslate);

export const MaterialStatusDTOSchema = materialStatusSchemas.MaterialStatusDTOSchema;
export const MaterialStatusSchema = materialStatusSchemas.MaterialStatusSchema;
export const MaterialStatusKeySchema = materialStatusSchemas.MaterialStatusKeySchema;
export const MaterialStatusNewSchema = materialStatusSchemas.MaterialStatusNewSchema;
export const MaterialStatusUpdSchema = materialStatusSchemas.MaterialStatusUpdSchema;
export const MaterialStatusUpdateSchema = materialStatusSchemas.MaterialStatusUpdateSchema;

export const materialStatusFromDTO = (
	dto: unknown,
): MaterialStatus => {
	const parsedDTO = v.parse(MaterialStatusDTOSchema, dto);

	return v.parse(MaterialStatusSchema, {
		...parsedDTO,
		created_at: new Date(parsedDTO.created_at),
	});
};
