// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialConsumptionItemList } from "@/types/materialConsumptionItemList.gen";

export const createMaterialConsumptionItemListSchemas = (t: TranslateFn) => {
	const {
		IntSchema,
		IdSchema,
		NumberSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialConsumptionItemListDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_consumption_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
	});

	const MaterialConsumptionItemListSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_consumption_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
	});

	return {
		MaterialConsumptionItemListDTOSchema,
		MaterialConsumptionItemListSchema,
	};
};

const materialConsumptionItemListSchemas = createMaterialConsumptionItemListSchemas(defaultTranslate);

export const MaterialConsumptionItemListDTOSchema = materialConsumptionItemListSchemas.MaterialConsumptionItemListDTOSchema;
export const MaterialConsumptionItemListSchema = materialConsumptionItemListSchemas.MaterialConsumptionItemListSchema;

export const materialConsumptionItemListFromDTO = (
	dto: unknown,
): MaterialConsumptionItemList => {
	const parsedDTO = v.parse(MaterialConsumptionItemListDTOSchema, dto);

	return v.parse(MaterialConsumptionItemListSchema, {
		...parsedDTO,
	});
};
