// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialList } from "@/types/materialList.gen";

export const createMaterialListSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		TextSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialListDTOSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: v.nullable(TextSchema),
		measure_unit_id: IdSchema,
		measure_unit: AttrsSchema,
		material_type_id: IdSchema,
		material_type: AttrsSchema,
		is_active: v.boolean(),
		balances: AttrsSchema,
	});

	const MaterialListSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: v.nullable(TextSchema),
		measure_unit_id: IdSchema,
		measure_unit: AttrsSchema,
		material_type_id: IdSchema,
		material_type: AttrsSchema,
		is_active: v.boolean(),
		balances: AttrsSchema,
	});

	return {
		MaterialListDTOSchema,
		MaterialListSchema,
	};
};

const materialListSchemas = createMaterialListSchemas(defaultTranslate);

export const MaterialListDTOSchema = materialListSchemas.MaterialListDTOSchema;
export const MaterialListSchema = materialListSchemas.MaterialListSchema;

export const materialListFromDTO = (
	dto: unknown,
): MaterialList => {
	const parsedDTO = v.parse(MaterialListDTOSchema, dto);

	return v.parse(MaterialListSchema, {
		...parsedDTO,
	});
};
