// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialConsumptionList } from "@/types/materialConsumptionList.gen";

export const createMaterialConsumptionListSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialConsumptionListDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		construction_site: AttrsSchema,
	});

	const MaterialConsumptionListSchema = v.object({
		id: IdSchema,
		date: v.date(),
		construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		construction_site: AttrsSchema,
	});

	return {
		MaterialConsumptionListDTOSchema,
		MaterialConsumptionListSchema,
	};
};

const materialConsumptionListSchemas = createMaterialConsumptionListSchemas(defaultTranslate);

export const MaterialConsumptionListDTOSchema = materialConsumptionListSchemas.MaterialConsumptionListDTOSchema;
export const MaterialConsumptionListSchema = materialConsumptionListSchemas.MaterialConsumptionListSchema;

export const materialConsumptionListFromDTO = (
	dto: unknown,
): MaterialConsumptionList => {
	const parsedDTO = v.parse(MaterialConsumptionListDTOSchema, dto);

	return v.parse(MaterialConsumptionListSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
