// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialConsumptionItem } from "@/types/materialConsumptionItem.gen";

export const createMaterialConsumptionItemSchemas = (t: TranslateFn) => {
	const {
		IntSchema,
		IdSchema,
		NumberSchema,
	} = createCommonSchemas(t);

	const MaterialConsumptionItemDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_consumption_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
	});

	const MaterialConsumptionItemSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_consumption_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
	});

	const MaterialConsumptionItemKeySchema = v.pick(
		MaterialConsumptionItemSchema,
		[
			"id",
		],
	);
	const MaterialConsumptionItemNewSchema = v.pick(
		MaterialConsumptionItemSchema,
		[
			"line_num",
			"material_consumption_id",
			"material_id",
			"measure_unit_id",
			"quant",
		],
	);
	const MaterialConsumptionItemUpdSchema = v.partial(v.pick(
		MaterialConsumptionItemSchema,
		[
			"line_num",
			"material_consumption_id",
			"material_id",
			"measure_unit_id",
			"quant",
		],
	));

	const MaterialConsumptionItemUpdateSchema = v.object({
		key: MaterialConsumptionItemKeySchema,
		model: MaterialConsumptionItemUpdSchema,
	});
	return {
		MaterialConsumptionItemDTOSchema,
		MaterialConsumptionItemSchema,
		MaterialConsumptionItemKeySchema,
		MaterialConsumptionItemNewSchema,
		MaterialConsumptionItemUpdSchema,
		MaterialConsumptionItemUpdateSchema,
	};
};

const materialConsumptionItemSchemas = createMaterialConsumptionItemSchemas(defaultTranslate);

export const MaterialConsumptionItemDTOSchema = materialConsumptionItemSchemas.MaterialConsumptionItemDTOSchema;
export const MaterialConsumptionItemSchema = materialConsumptionItemSchemas.MaterialConsumptionItemSchema;
export const MaterialConsumptionItemKeySchema = materialConsumptionItemSchemas.MaterialConsumptionItemKeySchema;
export const MaterialConsumptionItemNewSchema = materialConsumptionItemSchemas.MaterialConsumptionItemNewSchema;
export const MaterialConsumptionItemUpdSchema = materialConsumptionItemSchemas.MaterialConsumptionItemUpdSchema;
export const MaterialConsumptionItemUpdateSchema = materialConsumptionItemSchemas.MaterialConsumptionItemUpdateSchema;

export const materialConsumptionItemFromDTO = (
	dto: unknown,
): MaterialConsumptionItem => {
	const parsedDTO = v.parse(MaterialConsumptionItemDTOSchema, dto);

	return v.parse(MaterialConsumptionItemSchema, {
		...parsedDTO,
	});
};
