// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialRequestItem } from "@/types/materialRequestItem.gen";

export const createMaterialRequestItemSchemas = (t: TranslateFn) => {
	const {
		DateStringSchema,
		IntSchema,
		IdSchema,
		NumberSchema,
	} = createCommonSchemas(t);

	const MaterialRequestItemDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_request_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		supplier_id: v.nullable(IdSchema),
		required_date: v.nullable(DateStringSchema),
		order_importance_id: IdSchema,
		status_id: IdSchema,
	});

	const MaterialRequestItemSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_request_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		supplier_id: v.nullable(IdSchema),
		required_date: v.nullable(v.date()),
		order_importance_id: IdSchema,
		status_id: IdSchema,
	});

	const MaterialRequestItemKeySchema = v.pick(
		MaterialRequestItemSchema,
		[
			"id",
		],
	);
	const MaterialRequestItemNewSchema = v.pick(
		MaterialRequestItemSchema,
		[
			"line_num",
			"material_request_id",
			"material_id",
			"measure_unit_id",
			"quant",
			"supplier_id",
			"required_date",
			"order_importance_id",
			"status_id",
		],
	);
	const MaterialRequestItemUpdSchema = v.partial(v.pick(
		MaterialRequestItemSchema,
		[
			"line_num",
			"material_request_id",
			"material_id",
			"measure_unit_id",
			"quant",
			"supplier_id",
			"required_date",
			"order_importance_id",
			"status_id",
		],
	));

	const MaterialRequestItemUpdateSchema = v.object({
		key: MaterialRequestItemKeySchema,
		model: MaterialRequestItemUpdSchema,
	});
	return {
		MaterialRequestItemDTOSchema,
		MaterialRequestItemSchema,
		MaterialRequestItemKeySchema,
		MaterialRequestItemNewSchema,
		MaterialRequestItemUpdSchema,
		MaterialRequestItemUpdateSchema,
	};
};

const materialRequestItemSchemas = createMaterialRequestItemSchemas(defaultTranslate);

export const MaterialRequestItemDTOSchema = materialRequestItemSchemas.MaterialRequestItemDTOSchema;
export const MaterialRequestItemSchema = materialRequestItemSchemas.MaterialRequestItemSchema;
export const MaterialRequestItemKeySchema = materialRequestItemSchemas.MaterialRequestItemKeySchema;
export const MaterialRequestItemNewSchema = materialRequestItemSchemas.MaterialRequestItemNewSchema;
export const MaterialRequestItemUpdSchema = materialRequestItemSchemas.MaterialRequestItemUpdSchema;
export const MaterialRequestItemUpdateSchema = materialRequestItemSchemas.MaterialRequestItemUpdateSchema;

export const materialRequestItemFromDTO = (
	dto: unknown,
): MaterialRequestItem => {
	const parsedDTO = v.parse(MaterialRequestItemDTOSchema, dto);

	return v.parse(MaterialRequestItemSchema, {
		...parsedDTO,
		required_date: parsedDTO.required_date === null ? null : new Date(parsedDTO.required_date),
	});
};
