// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialConsumption } from "@/types/materialConsumption.gen";

export const createMaterialConsumptionSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const MaterialConsumptionDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
	});

	const MaterialConsumptionSchema = v.object({
		id: IdSchema,
		date: v.date(),
		construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
	});

	const MaterialConsumptionKeySchema = v.pick(
		MaterialConsumptionSchema,
		[
			"id",
		],
	);
	const MaterialConsumptionNewSchema = v.pick(
		MaterialConsumptionSchema,
		[
			"date",
			"construction_site_id",
			"comment",
		],
	);
	const MaterialConsumptionUpdSchema = v.partial(v.pick(
		MaterialConsumptionSchema,
		[
			"date",
			"construction_site_id",
			"comment",
		],
	));

	const MaterialConsumptionUpdateSchema = v.object({
		key: MaterialConsumptionKeySchema,
		model: MaterialConsumptionUpdSchema,
	});
	return {
		MaterialConsumptionDTOSchema,
		MaterialConsumptionSchema,
		MaterialConsumptionKeySchema,
		MaterialConsumptionNewSchema,
		MaterialConsumptionUpdSchema,
		MaterialConsumptionUpdateSchema,
	};
};

const materialConsumptionSchemas = createMaterialConsumptionSchemas(defaultTranslate);

export const MaterialConsumptionDTOSchema = materialConsumptionSchemas.MaterialConsumptionDTOSchema;
export const MaterialConsumptionSchema = materialConsumptionSchemas.MaterialConsumptionSchema;
export const MaterialConsumptionKeySchema = materialConsumptionSchemas.MaterialConsumptionKeySchema;
export const MaterialConsumptionNewSchema = materialConsumptionSchemas.MaterialConsumptionNewSchema;
export const MaterialConsumptionUpdSchema = materialConsumptionSchemas.MaterialConsumptionUpdSchema;
export const MaterialConsumptionUpdateSchema = materialConsumptionSchemas.MaterialConsumptionUpdateSchema;

export const materialConsumptionFromDTO = (
	dto: unknown,
): MaterialConsumption => {
	const parsedDTO = v.parse(MaterialConsumptionDTOSchema, dto);

	return v.parse(MaterialConsumptionSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
