// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialTransferItem } from "@/types/materialTransferItem.gen";

export const createMaterialTransferItemSchemas = (t: TranslateFn) => {
	const {
		IntSchema,
		IdSchema,
		NumberSchema,
	} = createCommonSchemas(t);

	const MaterialTransferItemDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_transfer_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
	});

	const MaterialTransferItemSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_transfer_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
	});

	const MaterialTransferItemKeySchema = v.pick(
		MaterialTransferItemSchema,
		[
			"id",
		],
	);
	const MaterialTransferItemNewSchema = v.pick(
		MaterialTransferItemSchema,
		[
			"line_num",
			"material_transfer_id",
			"material_id",
			"measure_unit_id",
			"quant",
		],
	);
	const MaterialTransferItemUpdSchema = v.partial(v.pick(
		MaterialTransferItemSchema,
		[
			"line_num",
			"material_transfer_id",
			"material_id",
			"measure_unit_id",
			"quant",
		],
	));

	const MaterialTransferItemUpdateSchema = v.object({
		key: MaterialTransferItemKeySchema,
		model: MaterialTransferItemUpdSchema,
	});
	return {
		MaterialTransferItemDTOSchema,
		MaterialTransferItemSchema,
		MaterialTransferItemKeySchema,
		MaterialTransferItemNewSchema,
		MaterialTransferItemUpdSchema,
		MaterialTransferItemUpdateSchema,
	};
};

const materialTransferItemSchemas = createMaterialTransferItemSchemas(defaultTranslate);

export const MaterialTransferItemDTOSchema = materialTransferItemSchemas.MaterialTransferItemDTOSchema;
export const MaterialTransferItemSchema = materialTransferItemSchemas.MaterialTransferItemSchema;
export const MaterialTransferItemKeySchema = materialTransferItemSchemas.MaterialTransferItemKeySchema;
export const MaterialTransferItemNewSchema = materialTransferItemSchemas.MaterialTransferItemNewSchema;
export const MaterialTransferItemUpdSchema = materialTransferItemSchemas.MaterialTransferItemUpdSchema;
export const MaterialTransferItemUpdateSchema = materialTransferItemSchemas.MaterialTransferItemUpdateSchema;

export const materialTransferItemFromDTO = (
	dto: unknown,
): MaterialTransferItem => {
	const parsedDTO = v.parse(MaterialTransferItemDTOSchema, dto);

	return v.parse(MaterialTransferItemSchema, {
		...parsedDTO,
	});
};
