// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import {
	createCommonSchemas,
	defaultTranslate,
	type TranslateFn,
} from "@/schemas/common";
import type { MaterialRequest } from "@/types/materialRequest.gen";

export const createMaterialRequestSchemas = (t: TranslateFn) => {
	const { TextSchema, DateStringSchema, IntSchema, IdSchema } =
		createCommonSchemas(t);

	const MaterialRequestDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		construction_site_id: IdSchema,
		construction_manager_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		status_id: IdSchema,
	});

	const MaterialRequestSchema = v.object({
		id: IdSchema,
		date: v.date(),
		construction_site_id: IdSchema,
		construction_manager_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		status_id: IdSchema,
	});

	const MaterialRequestKeySchema = v.pick(MaterialRequestSchema, ["id"]);
	const MaterialRequestNewSchema = v.pick(MaterialRequestSchema, [
		"date",
		"construction_site_id",
		"construction_manager_id",
		"comment",
	]);
	const MaterialRequestUpdSchema = v.partial(
		v.pick(MaterialRequestSchema, [
			"date",
			"construction_site_id",
			"construction_manager_id",
			"comment",
		]),
	);

	const MaterialRequestUpdateSchema = v.object({
		key: MaterialRequestKeySchema,
		model: MaterialRequestUpdSchema,
	});
	return {
		MaterialRequestDTOSchema,
		MaterialRequestSchema,
		MaterialRequestKeySchema,
		MaterialRequestNewSchema,
		MaterialRequestUpdSchema,
		MaterialRequestUpdateSchema,
	};
};

const materialRequestSchemas = createMaterialRequestSchemas(defaultTranslate);

export const MaterialRequestDTOSchema =
	materialRequestSchemas.MaterialRequestDTOSchema;
export const MaterialRequestSchema =
	materialRequestSchemas.MaterialRequestSchema;
export const MaterialRequestKeySchema =
	materialRequestSchemas.MaterialRequestKeySchema;
export const MaterialRequestNewSchema =
	materialRequestSchemas.MaterialRequestNewSchema;
export const MaterialRequestUpdSchema =
	materialRequestSchemas.MaterialRequestUpdSchema;
export const MaterialRequestUpdateSchema =
	materialRequestSchemas.MaterialRequestUpdateSchema;

export const materialRequestFromDTO = (dto: unknown): MaterialRequest => {
	const parsedDTO = v.parse(MaterialRequestDTOSchema, dto);

	return v.parse(MaterialRequestSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
