// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { Material } from "@/types/material.gen";

export const createMaterialSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		TextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const MaterialDTOSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: v.nullable(TextSchema),
		measure_unit_id: IdSchema,
		material_type_id: IdSchema,
		is_active: v.boolean(),
	});

	const MaterialSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: v.nullable(TextSchema),
		measure_unit_id: IdSchema,
		material_type_id: IdSchema,
		is_active: v.boolean(),
	});

	const MaterialKeySchema = v.pick(
		MaterialSchema,
		[
			"id",
		],
	);
	const MaterialNewSchema = v.pick(
		MaterialSchema,
		[
			"name",
			"name_full",
			"measure_unit_id",
			"material_type_id",
			"is_active",
		],
	);
	const MaterialUpdSchema = v.partial(v.pick(
		MaterialSchema,
		[
			"name",
			"name_full",
			"measure_unit_id",
			"material_type_id",
			"is_active",
		],
	));

	const MaterialUpdateSchema = v.object({
		key: MaterialKeySchema,
		model: MaterialUpdSchema,
	});
	return {
		MaterialDTOSchema,
		MaterialSchema,
		MaterialKeySchema,
		MaterialNewSchema,
		MaterialUpdSchema,
		MaterialUpdateSchema,
	};
};

const materialSchemas = createMaterialSchemas(defaultTranslate);

export const MaterialDTOSchema = materialSchemas.MaterialDTOSchema;
export const MaterialSchema = materialSchemas.MaterialSchema;
export const MaterialKeySchema = materialSchemas.MaterialKeySchema;
export const MaterialNewSchema = materialSchemas.MaterialNewSchema;
export const MaterialUpdSchema = materialSchemas.MaterialUpdSchema;
export const MaterialUpdateSchema = materialSchemas.MaterialUpdateSchema;

export const materialFromDTO = (
	dto: unknown,
): Material => {
	const parsedDTO = v.parse(MaterialDTOSchema, dto);

	return v.parse(MaterialSchema, {
		...parsedDTO,
	});
};
