// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import {
	createCommonSchemas,
	defaultTranslate,
	type TranslateFn,
} from "@/schemas/common";
import type { MaterialRequestList } from "@/types/materialRequestList.gen";

export const createMaterialRequestListSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialRequestListDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		construction_site_id: IdSchema,
		construction_manager_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		construction_site: AttrsSchema,
		construction_manager: AttrsSchema,
	});

	const MaterialRequestListSchema = v.object({
		id: IdSchema,
		date: v.date(),
		construction_site_id: IdSchema,
		construction_manager_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		construction_site: AttrsSchema,
		construction_manager: AttrsSchema,
	});

	return {
		MaterialRequestListDTOSchema,
		MaterialRequestListSchema,
	};
};

const materialRequestListSchemas =
	createMaterialRequestListSchemas(defaultTranslate);

export const MaterialRequestListDTOSchema =
	materialRequestListSchemas.MaterialRequestListDTOSchema;
export const MaterialRequestListSchema =
	materialRequestListSchemas.MaterialRequestListSchema;

export const materialRequestListFromDTO = (
	dto: unknown,
): MaterialRequestList => {
	const parsedDTO = v.parse(MaterialRequestListDTOSchema, dto);

	return v.parse(MaterialRequestListSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
