// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialReceiptList } from "@/types/materialReceiptList.gen";

export const createMaterialReceiptListSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialReceiptListDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		construction_site_id: v.nullable(IdSchema),
		supplier_id: IdSchema,
		number: RequiredTextSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		construction_site: v.nullable(AttrsSchema),
		supplier: AttrsSchema,
	});

	const MaterialReceiptListSchema = v.object({
		id: IdSchema,
		date: v.date(),
		construction_site_id: v.nullable(IdSchema),
		supplier_id: IdSchema,
		number: RequiredTextSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		construction_site: v.nullable(AttrsSchema),
		supplier: AttrsSchema,
	});

	return {
		MaterialReceiptListDTOSchema,
		MaterialReceiptListSchema,
	};
};

const materialReceiptListSchemas = createMaterialReceiptListSchemas(defaultTranslate);

export const MaterialReceiptListDTOSchema = materialReceiptListSchemas.MaterialReceiptListDTOSchema;
export const MaterialReceiptListSchema = materialReceiptListSchemas.MaterialReceiptListSchema;

export const materialReceiptListFromDTO = (
	dto: unknown,
): MaterialReceiptList => {
	const parsedDTO = v.parse(MaterialReceiptListDTOSchema, dto);

	return v.parse(MaterialReceiptListSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
