// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialTransferItemList } from "@/types/materialTransferItemList.gen";

export const createMaterialTransferItemListSchemas = (t: TranslateFn) => {
	const {
		IntSchema,
		IdSchema,
		NumberSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialTransferItemListDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_transfer_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
	});

	const MaterialTransferItemListSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_transfer_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
	});

	return {
		MaterialTransferItemListDTOSchema,
		MaterialTransferItemListSchema,
	};
};

const materialTransferItemListSchemas = createMaterialTransferItemListSchemas(defaultTranslate);

export const MaterialTransferItemListDTOSchema = materialTransferItemListSchemas.MaterialTransferItemListDTOSchema;
export const MaterialTransferItemListSchema = materialTransferItemListSchemas.MaterialTransferItemListSchema;

export const materialTransferItemListFromDTO = (
	dto: unknown,
): MaterialTransferItemList => {
	const parsedDTO = v.parse(MaterialTransferItemListDTOSchema, dto);

	return v.parse(MaterialTransferItemListSchema, {
		...parsedDTO,
	});
};
