// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialRequestStatus } from "@/types/materialRequestStatus.gen";

export const createMaterialRequestStatusSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		RequiredTextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const MaterialRequestStatusDTOSchema = v.object({
		id: IdSchema,
		code: RequiredStringSchema,
		name: RequiredTextSchema,
	});

	const MaterialRequestStatusSchema = v.object({
		id: IdSchema,
		code: RequiredStringSchema,
		name: RequiredTextSchema,
	});

	const MaterialRequestStatusKeySchema = v.pick(
		MaterialRequestStatusSchema,
		[
			"id",
		],
	);
	const MaterialRequestStatusUpdSchema = v.partial(v.pick(
		MaterialRequestStatusSchema,
		[
			"name",
		],
	));

	const MaterialRequestStatusUpdateSchema = v.object({
		key: MaterialRequestStatusKeySchema,
		model: MaterialRequestStatusUpdSchema,
	});
	return {
		MaterialRequestStatusDTOSchema,
		MaterialRequestStatusSchema,
		MaterialRequestStatusKeySchema,
		MaterialRequestStatusUpdSchema,
		MaterialRequestStatusUpdateSchema,
	};
};

const materialRequestStatusSchemas = createMaterialRequestStatusSchemas(defaultTranslate);

export const MaterialRequestStatusDTOSchema = materialRequestStatusSchemas.MaterialRequestStatusDTOSchema;
export const MaterialRequestStatusSchema = materialRequestStatusSchemas.MaterialRequestStatusSchema;
export const MaterialRequestStatusKeySchema = materialRequestStatusSchemas.MaterialRequestStatusKeySchema;
export const MaterialRequestStatusUpdSchema = materialRequestStatusSchemas.MaterialRequestStatusUpdSchema;
export const MaterialRequestStatusUpdateSchema = materialRequestStatusSchemas.MaterialRequestStatusUpdateSchema;

export const materialRequestStatusFromDTO = (
	dto: unknown,
): MaterialRequestStatus => {
	const parsedDTO = v.parse(MaterialRequestStatusDTOSchema, dto);

	return v.parse(MaterialRequestStatusSchema, {
		...parsedDTO,
	});
};
