// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialReceipt } from "@/types/materialReceipt.gen";

export const createMaterialReceiptSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const MaterialReceiptDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		construction_site_id: v.nullable(IdSchema),
		supplier_id: IdSchema,
		number: RequiredTextSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
	});

	const MaterialReceiptSchema = v.object({
		id: IdSchema,
		date: v.date(),
		construction_site_id: v.nullable(IdSchema),
		supplier_id: IdSchema,
		number: RequiredTextSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
	});

	const MaterialReceiptKeySchema = v.pick(
		MaterialReceiptSchema,
		[
			"id",
		],
	);
	const MaterialReceiptNewSchema = v.pick(
		MaterialReceiptSchema,
		[
			"date",
			"construction_site_id",
			"supplier_id",
			"number",
			"comment",
		],
	);
	const MaterialReceiptUpdSchema = v.partial(v.pick(
		MaterialReceiptSchema,
		[
			"date",
			"construction_site_id",
			"supplier_id",
			"number",
			"comment",
		],
	));

	const MaterialReceiptUpdateSchema = v.object({
		key: MaterialReceiptKeySchema,
		model: MaterialReceiptUpdSchema,
	});
	return {
		MaterialReceiptDTOSchema,
		MaterialReceiptSchema,
		MaterialReceiptKeySchema,
		MaterialReceiptNewSchema,
		MaterialReceiptUpdSchema,
		MaterialReceiptUpdateSchema,
	};
};

const materialReceiptSchemas = createMaterialReceiptSchemas(defaultTranslate);

export const MaterialReceiptDTOSchema = materialReceiptSchemas.MaterialReceiptDTOSchema;
export const MaterialReceiptSchema = materialReceiptSchemas.MaterialReceiptSchema;
export const MaterialReceiptKeySchema = materialReceiptSchemas.MaterialReceiptKeySchema;
export const MaterialReceiptNewSchema = materialReceiptSchemas.MaterialReceiptNewSchema;
export const MaterialReceiptUpdSchema = materialReceiptSchemas.MaterialReceiptUpdSchema;
export const MaterialReceiptUpdateSchema = materialReceiptSchemas.MaterialReceiptUpdateSchema;

export const materialReceiptFromDTO = (
	dto: unknown,
): MaterialReceipt => {
	const parsedDTO = v.parse(MaterialReceiptDTOSchema, dto);

	return v.parse(MaterialReceiptSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
