// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialReceiptItem } from "@/types/materialReceiptItem.gen";

export const createMaterialReceiptItemSchemas = (t: TranslateFn) => {
	const {
		IntSchema,
		IdSchema,
		NumberSchema,
	} = createCommonSchemas(t);

	const MaterialReceiptItemDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_receipt_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		construction_site_id: v.nullable(IdSchema),
		quant: NumberSchema,
		price: NumberSchema,
		amount: NumberSchema,
		vat_percent: NumberSchema,
		vat_amount: NumberSchema,
	});

	const MaterialReceiptItemSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_receipt_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		construction_site_id: v.nullable(IdSchema),
		quant: NumberSchema,
		price: NumberSchema,
		amount: NumberSchema,
		vat_percent: NumberSchema,
		vat_amount: NumberSchema,
	});

	const MaterialReceiptItemKeySchema = v.pick(
		MaterialReceiptItemSchema,
		[
			"id",
		],
	);
	const MaterialReceiptItemNewSchema = v.pick(
		MaterialReceiptItemSchema,
		[
			"line_num",
			"material_receipt_id",
			"material_id",
			"measure_unit_id",
			"construction_site_id",
			"quant",
			"price",
			"amount",
			"vat_percent",
			"vat_amount",
		],
	);
	const MaterialReceiptItemUpdSchema = v.partial(v.pick(
		MaterialReceiptItemSchema,
		[
			"line_num",
			"material_receipt_id",
			"material_id",
			"measure_unit_id",
			"construction_site_id",
			"quant",
			"price",
			"amount",
			"vat_percent",
			"vat_amount",
		],
	));

	const MaterialReceiptItemUpdateSchema = v.object({
		key: MaterialReceiptItemKeySchema,
		model: MaterialReceiptItemUpdSchema,
	});
	return {
		MaterialReceiptItemDTOSchema,
		MaterialReceiptItemSchema,
		MaterialReceiptItemKeySchema,
		MaterialReceiptItemNewSchema,
		MaterialReceiptItemUpdSchema,
		MaterialReceiptItemUpdateSchema,
	};
};

const materialReceiptItemSchemas = createMaterialReceiptItemSchemas(defaultTranslate);

export const MaterialReceiptItemDTOSchema = materialReceiptItemSchemas.MaterialReceiptItemDTOSchema;
export const MaterialReceiptItemSchema = materialReceiptItemSchemas.MaterialReceiptItemSchema;
export const MaterialReceiptItemKeySchema = materialReceiptItemSchemas.MaterialReceiptItemKeySchema;
export const MaterialReceiptItemNewSchema = materialReceiptItemSchemas.MaterialReceiptItemNewSchema;
export const MaterialReceiptItemUpdSchema = materialReceiptItemSchemas.MaterialReceiptItemUpdSchema;
export const MaterialReceiptItemUpdateSchema = materialReceiptItemSchemas.MaterialReceiptItemUpdateSchema;

export const materialReceiptItemFromDTO = (
	dto: unknown,
): MaterialReceiptItem => {
	const parsedDTO = v.parse(MaterialReceiptItemDTOSchema, dto);

	return v.parse(MaterialReceiptItemSchema, {
		...parsedDTO,
	});
};
