// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialReceiptItemList } from "@/types/materialReceiptItemList.gen";

export const createMaterialReceiptItemListSchemas = (t: TranslateFn) => {
	const {
		IntSchema,
		IdSchema,
		NumberSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialReceiptItemListDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_receipt_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		construction_site_id: v.nullable(IdSchema),
		quant: NumberSchema,
		price: NumberSchema,
		amount: NumberSchema,
		vat_percent: NumberSchema,
		vat_amount: NumberSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
		construction_site: AttrsSchema,
	});

	const MaterialReceiptItemListSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_receipt_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		construction_site_id: v.nullable(IdSchema),
		quant: NumberSchema,
		price: NumberSchema,
		amount: NumberSchema,
		vat_percent: NumberSchema,
		vat_amount: NumberSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
		construction_site: AttrsSchema,
	});

	return {
		MaterialReceiptItemListDTOSchema,
		MaterialReceiptItemListSchema,
	};
};

const materialReceiptItemListSchemas = createMaterialReceiptItemListSchemas(defaultTranslate);

export const MaterialReceiptItemListDTOSchema = materialReceiptItemListSchemas.MaterialReceiptItemListDTOSchema;
export const MaterialReceiptItemListSchema = materialReceiptItemListSchemas.MaterialReceiptItemListSchema;

export const materialReceiptItemListFromDTO = (
	dto: unknown,
): MaterialReceiptItemList => {
	const parsedDTO = v.parse(MaterialReceiptItemListDTOSchema, dto);

	return v.parse(MaterialReceiptItemListSchema, {
		...parsedDTO,
	});
};
