// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import {
	createMaterialStatusTypeSchemas,
} from "@/schemas/enums/materialStatusType.gen";
import type { MaterialStatusList } from "@/types/materialStatusList.gen";

export const createMaterialStatusListSchemas = (t: TranslateFn) => {
	const {
		DateStringSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);
	const { MaterialStatusTypeSchema } = createMaterialStatusTypeSchemas(t);

	const MaterialStatusListDTOSchema = v.object({
		id: IdSchema,
		created_at: DateStringSchema,
		material_id: IdSchema,
		material: AttrsSchema,
		status: MaterialStatusTypeSchema,
		is_active: v.boolean(),
	});

	const MaterialStatusListSchema = v.object({
		id: IdSchema,
		created_at: v.date(),
		material_id: IdSchema,
		material: AttrsSchema,
		status: MaterialStatusTypeSchema,
		is_active: v.boolean(),
	});

	return {
		MaterialStatusListDTOSchema,
		MaterialStatusListSchema,
	};
};

const materialStatusListSchemas = createMaterialStatusListSchemas(defaultTranslate);

export const MaterialStatusListDTOSchema = materialStatusListSchemas.MaterialStatusListDTOSchema;
export const MaterialStatusListSchema = materialStatusListSchemas.MaterialStatusListSchema;

export const materialStatusListFromDTO = (
	dto: unknown,
): MaterialStatusList => {
	const parsedDTO = v.parse(MaterialStatusListDTOSchema, dto);

	return v.parse(MaterialStatusListSchema, {
		...parsedDTO,
		created_at: new Date(parsedDTO.created_at),
	});
};
