// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialType } from "@/types/materialType.gen";

export const createMaterialTypeSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		RequiredTextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const MaterialTypeDTOSchema = v.object({
		id: IdSchema,
		code: RequiredStringSchema,
		name: RequiredTextSchema,
		is_active: v.boolean(),
	});

	const MaterialTypeSchema = v.object({
		id: IdSchema,
		code: RequiredStringSchema,
		name: RequiredTextSchema,
		is_active: v.boolean(),
	});

	const MaterialTypeKeySchema = v.pick(
		MaterialTypeSchema,
		[
			"id",
		],
	);
	const MaterialTypeNewSchema = v.pick(
		MaterialTypeSchema,
		[
			"code",
			"name",
			"is_active",
		],
	);
	const MaterialTypeUpdSchema = v.partial(v.pick(
		MaterialTypeSchema,
		[
			"code",
			"name",
			"is_active",
		],
	));

	const MaterialTypeUpdateSchema = v.object({
		key: MaterialTypeKeySchema,
		model: MaterialTypeUpdSchema,
	});
	return {
		MaterialTypeDTOSchema,
		MaterialTypeSchema,
		MaterialTypeKeySchema,
		MaterialTypeNewSchema,
		MaterialTypeUpdSchema,
		MaterialTypeUpdateSchema,
	};
};

const materialTypeSchemas = createMaterialTypeSchemas(defaultTranslate);

export const MaterialTypeDTOSchema = materialTypeSchemas.MaterialTypeDTOSchema;
export const MaterialTypeSchema = materialTypeSchemas.MaterialTypeSchema;
export const MaterialTypeKeySchema = materialTypeSchemas.MaterialTypeKeySchema;
export const MaterialTypeNewSchema = materialTypeSchemas.MaterialTypeNewSchema;
export const MaterialTypeUpdSchema = materialTypeSchemas.MaterialTypeUpdSchema;
export const MaterialTypeUpdateSchema = materialTypeSchemas.MaterialTypeUpdateSchema;

export const materialTypeFromDTO = (
	dto: unknown,
): MaterialType => {
	const parsedDTO = v.parse(MaterialTypeDTOSchema, dto);

	return v.parse(MaterialTypeSchema, {
		...parsedDTO,
	});
};
