// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import {
	createCommonSchemas,
	defaultTranslate,
	type TranslateFn,
} from "@/schemas/common";
import type { MaterialRequestItemList } from "@/types/materialRequestItemList.gen";

export const createMaterialRequestItemListSchemas = (t: TranslateFn) => {
	const {
		DateStringSchema,
		IntSchema,
		IdSchema,
		NumberSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialRequestItemListDTOSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_request_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		supplier_id: v.nullable(IdSchema),
		required_date: v.nullable(DateStringSchema),
		order_importance_id: IdSchema,
		status_id: IdSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
		supplier: v.nullable(AttrsSchema),
		order_importance: AttrsSchema,
		status: AttrsSchema,
	});

	const MaterialRequestItemListSchema = v.object({
		id: IdSchema,
		line_num: IntSchema,
		material_request_id: IdSchema,
		material_id: IdSchema,
		measure_unit_id: IdSchema,
		quant: NumberSchema,
		supplier_id: v.nullable(IdSchema),
		required_date: v.nullable(v.date()),
		order_importance_id: IdSchema,
		status_id: IdSchema,
		material: AttrsSchema,
		measure_unit: AttrsSchema,
		supplier: v.nullable(AttrsSchema),
		order_importance: AttrsSchema,
		status: AttrsSchema,
	});

	return {
		MaterialRequestItemListDTOSchema,
		MaterialRequestItemListSchema,
	};
};

const materialRequestItemListSchemas =
	createMaterialRequestItemListSchemas(defaultTranslate);

export const MaterialRequestItemListDTOSchema =
	materialRequestItemListSchemas.MaterialRequestItemListDTOSchema;
export const MaterialRequestItemListSchema =
	materialRequestItemListSchemas.MaterialRequestItemListSchema;

export const materialRequestItemListFromDTO = (
	dto: unknown,
): MaterialRequestItemList => {
	const parsedDTO = v.parse(MaterialRequestItemListDTOSchema, dto);

	return v.parse(MaterialRequestItemListSchema, {
		...parsedDTO,
		required_date:
			parsedDTO.required_date === null
				? null
				: new Date(parsedDTO.required_date),
	});
};
