// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaterialTransferList } from "@/types/materialTransferList.gen";

export const createMaterialTransferListSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		DateStringSchema,
		IntSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaterialTransferListDTOSchema = v.object({
		id: IdSchema,
		date: DateStringSchema,
		source_construction_site_id: IdSchema,
		destination_construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		source_construction_site: AttrsSchema,
		destination_construction_site: AttrsSchema,
	});

	const MaterialTransferListSchema = v.object({
		id: IdSchema,
		date: v.date(),
		source_construction_site_id: IdSchema,
		destination_construction_site_id: IdSchema,
		comment: v.nullable(TextSchema),
		version: IntSchema,
		source_construction_site: AttrsSchema,
		destination_construction_site: AttrsSchema,
	});

	return {
		MaterialTransferListDTOSchema,
		MaterialTransferListSchema,
	};
};

const materialTransferListSchemas = createMaterialTransferListSchemas(defaultTranslate);

export const MaterialTransferListDTOSchema = materialTransferListSchemas.MaterialTransferListDTOSchema;
export const MaterialTransferListSchema = materialTransferListSchemas.MaterialTransferListSchema;

export const materialTransferListFromDTO = (
	dto: unknown,
): MaterialTransferList => {
	const parsedDTO = v.parse(MaterialTransferListDTOSchema, dto);

	return v.parse(MaterialTransferListSchema, {
		...parsedDTO,
		date: new Date(parsedDTO.date),
	});
};
