// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaxUser } from "@/types/maxUser.gen";

export const createMaxUserSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaxUserDTOSchema = v.object({
		id: IdSchema,
		contact_id: v.nullable(IdSchema),
		max_user_id: IdSchema,
		username: v.nullable(TextSchema),
		avatar_url: v.nullable(TextSchema),
		raw_user: AttrsSchema,
		raw_user_with_photo: v.nullable(AttrsSchema),
		is_active: v.boolean(),
	});

	const MaxUserSchema = v.object({
		id: IdSchema,
		contact_id: v.nullable(IdSchema),
		max_user_id: IdSchema,
		username: v.nullable(TextSchema),
		avatar_url: v.nullable(TextSchema),
		raw_user: AttrsSchema,
		raw_user_with_photo: v.nullable(AttrsSchema),
		is_active: v.boolean(),
	});

	const MaxUserKeySchema = v.pick(
		MaxUserSchema,
		[
			"id",
		],
	);
	const MaxUserUpdSchema = v.partial(v.pick(
		MaxUserSchema,
		[
			"contact_id",
			"max_user_id",
			"username",
			"avatar_url",
			"raw_user",
			"raw_user_with_photo",
			"is_active",
		],
	));

	const MaxUserUpdateSchema = v.object({
		key: MaxUserKeySchema,
		model: MaxUserUpdSchema,
	});
	return {
		MaxUserDTOSchema,
		MaxUserSchema,
		MaxUserKeySchema,
		MaxUserUpdSchema,
		MaxUserUpdateSchema,
	};
};

const maxUserSchemas = createMaxUserSchemas(defaultTranslate);

export const MaxUserDTOSchema = maxUserSchemas.MaxUserDTOSchema;
export const MaxUserSchema = maxUserSchemas.MaxUserSchema;
export const MaxUserKeySchema = maxUserSchemas.MaxUserKeySchema;
export const MaxUserUpdSchema = maxUserSchemas.MaxUserUpdSchema;
export const MaxUserUpdateSchema = maxUserSchemas.MaxUserUpdateSchema;

export const maxUserFromDTO = (
	dto: unknown,
): MaxUser => {
	const parsedDTO = v.parse(MaxUserDTOSchema, dto);

	return v.parse(MaxUserSchema, {
		...parsedDTO,
	});
};
