// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MaxUserList } from "@/types/maxUserList.gen";

export const createMaxUserListSchemas = (t: TranslateFn) => {
	const {
		TextSchema,
		IdSchema,
		AttrsSchema,
	} = createCommonSchemas(t);

	const MaxUserListDTOSchema = v.object({
		id: IdSchema,
		contact: v.nullable(AttrsSchema),
		max_user_id: IdSchema,
		username: v.nullable(TextSchema),
		avatar_url: v.nullable(TextSchema),
		raw_user: AttrsSchema,
		is_active: v.boolean(),
	});

	const MaxUserListSchema = v.object({
		id: IdSchema,
		contact: v.nullable(AttrsSchema),
		max_user_id: IdSchema,
		username: v.nullable(TextSchema),
		avatar_url: v.nullable(TextSchema),
		raw_user: AttrsSchema,
		is_active: v.boolean(),
	});

	return {
		MaxUserListDTOSchema,
		MaxUserListSchema,
	};
};

const maxUserListSchemas = createMaxUserListSchemas(defaultTranslate);

export const MaxUserListDTOSchema = maxUserListSchemas.MaxUserListDTOSchema;
export const MaxUserListSchema = maxUserListSchemas.MaxUserListSchema;

export const maxUserListFromDTO = (
	dto: unknown,
): MaxUserList => {
	const parsedDTO = v.parse(MaxUserListDTOSchema, dto);

	return v.parse(MaxUserListSchema, {
		...parsedDTO,
	});
};
