// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { MeasureUnit } from "@/types/measureUnit.gen";

export const createMeasureUnitSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		StringSchema,
		RequiredTextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const MeasureUnitDTOSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: RequiredTextSchema,
		okei_code: StringSchema,
		is_active: v.boolean(),
	});

	const MeasureUnitSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: RequiredTextSchema,
		okei_code: StringSchema,
		is_active: v.boolean(),
	});

	const MeasureUnitKeySchema = v.pick(
		MeasureUnitSchema,
		[
			"id",
		],
	);
	const MeasureUnitNewSchema = v.pick(
		MeasureUnitSchema,
		[
			"name",
			"name_full",
			"okei_code",
			"is_active",
		],
	);
	const MeasureUnitUpdSchema = v.partial(v.pick(
		MeasureUnitSchema,
		[
			"name",
			"name_full",
			"okei_code",
			"is_active",
		],
	));

	const MeasureUnitUpdateSchema = v.object({
		key: MeasureUnitKeySchema,
		model: MeasureUnitUpdSchema,
	});
	return {
		MeasureUnitDTOSchema,
		MeasureUnitSchema,
		MeasureUnitKeySchema,
		MeasureUnitNewSchema,
		MeasureUnitUpdSchema,
		MeasureUnitUpdateSchema,
	};
};

const measureUnitSchemas = createMeasureUnitSchemas(defaultTranslate);

export const MeasureUnitDTOSchema = measureUnitSchemas.MeasureUnitDTOSchema;
export const MeasureUnitSchema = measureUnitSchemas.MeasureUnitSchema;
export const MeasureUnitKeySchema = measureUnitSchemas.MeasureUnitKeySchema;
export const MeasureUnitNewSchema = measureUnitSchemas.MeasureUnitNewSchema;
export const MeasureUnitUpdSchema = measureUnitSchemas.MeasureUnitUpdSchema;
export const MeasureUnitUpdateSchema = measureUnitSchemas.MeasureUnitUpdateSchema;

export const measureUnitFromDTO = (
	dto: unknown,
): MeasureUnit => {
	const parsedDTO = v.parse(MeasureUnitDTOSchema, dto);

	return v.parse(MeasureUnitSchema, {
		...parsedDTO,
	});
};
