// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { NotificationTemplate } from "@/types/notificationTemplate.gen";

export const createNotificationTemplateSchemas = (t: TranslateFn) => {
	const {
		RequiredTextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const NotificationTemplateDTOSchema = v.object({
		id: IdSchema,
		code: RequiredTextSchema,
		event: RequiredTextSchema,
		body_template: RequiredTextSchema,
		is_active: v.boolean(),
	});

	const NotificationTemplateSchema = v.object({
		id: IdSchema,
		code: RequiredTextSchema,
		event: RequiredTextSchema,
		body_template: RequiredTextSchema,
		is_active: v.boolean(),
	});

	const NotificationTemplateKeySchema = v.pick(
		NotificationTemplateSchema,
		[
			"id",
		],
	);
	const NotificationTemplateNewSchema = v.pick(
		NotificationTemplateSchema,
		[
			"code",
			"event",
			"body_template",
			"is_active",
		],
	);
	const NotificationTemplateUpdSchema = v.partial(v.pick(
		NotificationTemplateSchema,
		[
			"code",
			"event",
			"body_template",
			"is_active",
		],
	));

	const NotificationTemplateUpdateSchema = v.object({
		key: NotificationTemplateKeySchema,
		model: NotificationTemplateUpdSchema,
	});
	return {
		NotificationTemplateDTOSchema,
		NotificationTemplateSchema,
		NotificationTemplateKeySchema,
		NotificationTemplateNewSchema,
		NotificationTemplateUpdSchema,
		NotificationTemplateUpdateSchema,
	};
};

const notificationTemplateSchemas = createNotificationTemplateSchemas(defaultTranslate);

export const NotificationTemplateDTOSchema = notificationTemplateSchemas.NotificationTemplateDTOSchema;
export const NotificationTemplateSchema = notificationTemplateSchemas.NotificationTemplateSchema;
export const NotificationTemplateKeySchema = notificationTemplateSchemas.NotificationTemplateKeySchema;
export const NotificationTemplateNewSchema = notificationTemplateSchemas.NotificationTemplateNewSchema;
export const NotificationTemplateUpdSchema = notificationTemplateSchemas.NotificationTemplateUpdSchema;
export const NotificationTemplateUpdateSchema = notificationTemplateSchemas.NotificationTemplateUpdateSchema;

export const notificationTemplateFromDTO = (
	dto: unknown,
): NotificationTemplate => {
	const parsedDTO = v.parse(NotificationTemplateDTOSchema, dto);

	return v.parse(NotificationTemplateSchema, {
		...parsedDTO,
	});
};
