// Code generated by cmd/codegen. DO NOT EDIT.

import * as v from "valibot";

import { createCommonSchemas, defaultTranslate, type TranslateFn } from "@/schemas/common";
import type { Supplier } from "@/types/supplier.gen";

export const createSupplierSchemas = (t: TranslateFn) => {
	const {
		RequiredStringSchema,
		StringSchema,
		RequiredTextSchema,
		IdSchema,
	} = createCommonSchemas(t);

	const SupplierDTOSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: RequiredTextSchema,
		inn: RequiredStringSchema,
		kpp: v.nullable(StringSchema),
		is_active: v.boolean(),
	});

	const SupplierSchema = v.object({
		id: IdSchema,
		name: RequiredStringSchema,
		name_full: RequiredTextSchema,
		inn: RequiredStringSchema,
		kpp: v.nullable(StringSchema),
		is_active: v.boolean(),
	});

	const SupplierKeySchema = v.pick(
		SupplierSchema,
		[
			"id",
		],
	);
	const SupplierNewSchema = v.pick(
		SupplierSchema,
		[
			"name",
			"name_full",
			"inn",
			"kpp",
			"is_active",
		],
	);
	const SupplierUpdSchema = v.partial(v.pick(
		SupplierSchema,
		[
			"name",
			"name_full",
			"inn",
			"kpp",
			"is_active",
		],
	));

	const SupplierUpdateSchema = v.object({
		key: SupplierKeySchema,
		model: SupplierUpdSchema,
	});
	return {
		SupplierDTOSchema,
		SupplierSchema,
		SupplierKeySchema,
		SupplierNewSchema,
		SupplierUpdSchema,
		SupplierUpdateSchema,
	};
};

const supplierSchemas = createSupplierSchemas(defaultTranslate);

export const SupplierDTOSchema = supplierSchemas.SupplierDTOSchema;
export const SupplierSchema = supplierSchemas.SupplierSchema;
export const SupplierKeySchema = supplierSchemas.SupplierKeySchema;
export const SupplierNewSchema = supplierSchemas.SupplierNewSchema;
export const SupplierUpdSchema = supplierSchemas.SupplierUpdSchema;
export const SupplierUpdateSchema = supplierSchemas.SupplierUpdateSchema;

export const supplierFromDTO = (
	dto: unknown,
): Supplier => {
	const parsedDTO = v.parse(SupplierDTOSchema, dto);

	return v.parse(SupplierSchema, {
		...parsedDTO,
	});
};
