// Code generated by cmd/codegen. DO NOT EDIT.
// Frontend enum: material_status_type.

export const MATERIAL_STATUS_TYPE_VALUES = [
	"at_work",
	"on_maintenance",
] as const;

export type MaterialStatusType =
	(typeof MATERIAL_STATUS_TYPE_VALUES)[number];

export interface MaterialStatusTypeOption {
	value: MaterialStatusType;
	label: string;
}
