// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createConstructionSiteSchemas } from "@/schemas/constructionSite.gen";

export const useConstructionSiteSchemas = () => {
	const { t } = useI18n();

	return createConstructionSiteSchemas(t);
};
