// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createContactSchemas } from "@/schemas/contact.gen";

export const useContactSchemas = () => {
	const { t } = useI18n();

	return createContactSchemas(t);
};
