// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createEmployeePostSchemas } from "@/schemas/employeePost.gen";

export const useEmployeePostSchemas = () => {
	const { t } = useI18n();

	return createEmployeePostSchemas(t);
};
