// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createEntityContactSchemas } from "@/schemas/entityContact.gen";

export const useEntityContactSchemas = () => {
	const { t } = useI18n();

	return createEntityContactSchemas(t);
};
