// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialSchemas } from "@/schemas/material.gen";

export const useMaterialSchemas = () => {
	const { t } = useI18n();

	return createMaterialSchemas(t);
};
