// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialTypeSchemas } from "@/schemas/materialType.gen";

export const useMaterialTypeSchemas = () => {
	const { t } = useI18n();

	return createMaterialTypeSchemas(t);
};
