// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaxUserSchemas } from "@/schemas/maxUser.gen";

export const useMaxUserSchemas = () => {
	const { t } = useI18n();

	return createMaxUserSchemas(t);
};
