// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialReceiptItemSchemas } from "@/schemas/materialReceiptItem.gen";

export const useMaterialReceiptItemSchemas = () => {
	const { t } = useI18n();

	return createMaterialReceiptItemSchemas(t);
};
