// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialStatusSchemas } from "@/schemas/materialStatus.gen";

export const useMaterialStatusSchemas = () => {
	const { t } = useI18n();

	return createMaterialStatusSchemas(t);
};
