// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialRequestSchemas } from "@/schemas/materialRequest.gen";

export const useMaterialRequestSchemas = () => {
	const { t } = useI18n();

	return createMaterialRequestSchemas(t);
};
