// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMeasureUnitSchemas } from "@/schemas/measureUnit.gen";

export const useMeasureUnitSchemas = () => {
	const { t } = useI18n();

	return createMeasureUnitSchemas(t);
};
