// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialConsumptionSchemas } from "@/schemas/materialConsumption.gen";

export const useMaterialConsumptionSchemas = () => {
	const { t } = useI18n();

	return createMaterialConsumptionSchemas(t);
};
