// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialRequestItemSchemas } from "@/schemas/materialRequestItem.gen";

export const useMaterialRequestItemSchemas = () => {
	const { t } = useI18n();

	return createMaterialRequestItemSchemas(t);
};
