// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialTransferSchemas } from "@/schemas/materialTransfer.gen";

export const useMaterialTransferSchemas = () => {
	const { t } = useI18n();

	return createMaterialTransferSchemas(t);
};
