// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialReceiptSchemas } from "@/schemas/materialReceipt.gen";

export const useMaterialReceiptSchemas = () => {
	const { t } = useI18n();

	return createMaterialReceiptSchemas(t);
};
