// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialTransferItemSchemas } from "@/schemas/materialTransferItem.gen";

export const useMaterialTransferItemSchemas = () => {
	const { t } = useI18n();

	return createMaterialTransferItemSchemas(t);
};
