// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialRequestStatusSchemas } from "@/schemas/materialRequestStatus.gen";

export const useMaterialRequestStatusSchemas = () => {
	const { t } = useI18n();

	return createMaterialRequestStatusSchemas(t);
};
