// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createMaterialConsumptionItemSchemas } from "@/schemas/materialConsumptionItem.gen";

export const useMaterialConsumptionItemSchemas = () => {
	const { t } = useI18n();

	return createMaterialConsumptionItemSchemas(t);
};
