// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createNotificationTemplateSchemas } from "@/schemas/notificationTemplate.gen";

export const useNotificationTemplateSchemas = () => {
	const { t } = useI18n();

	return createNotificationTemplateSchemas(t);
};
