// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createOrderImportanceSchemas } from "@/schemas/orderImportance.gen";

export const useOrderImportanceSchemas = () => {
	const { t } = useI18n();

	return createOrderImportanceSchemas(t);
};
