// Code generated by cmd/codegen. DO NOT EDIT.

import { useI18n } from "vue-i18n";

import { createSupplierSchemas } from "@/schemas/supplier.gen";

export const useSupplierSchemas = () => {
	const { t } = useI18n();

	return createSupplierSchemas(t);
};
